# Generated by Django 6.0 on 2025-12-15 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_beta_tester',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'key'], name='idx_module_active_key')],
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_language', models.CharField(default='de', max_length=8)),
                ('learning_language', models.CharField(default='de', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('one_time', 'One-time'), ('subscription', 'Subscription'), ('lifetime', 'Lifetime')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='active', max_length=16)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_ref', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='accounts.module')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'module'], name='idx_ent_user_module'), models.Index(fields=['user', 'status'], name='idx_ent_user_status'), models.Index(fields=['module', 'status'], name='idx_ent_module_status'), models.Index(fields=['user', 'expires_at'], name='idx_ent_user_expires')],
                'constraints': [models.UniqueConstraint(fields=('user', 'module', 'plan', 'starts_at'), name='uniq_ent_user_module_plan_start')],
            },
        ),
    ]
