# Generated by Django 6.0 on 2026-01-25 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(help_text='Content season number, e.g. 1, 2, 3.')),
                ('title', models.CharField(blank=True, default='', help_text='Optional season title displayed in UI.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='entitlement',
            name='uniq_ent_user_module_plan_start',
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(db_index=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='module',
            field=models.ForeignKey(blank=True, help_text='If null, this entitlement is platform-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='accounts.module'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='plan',
            field=models.CharField(choices=[('trial_7d', 'Trial (7 days)'), ('m1', '1 month'), ('m3', '3 months'), ('m6', '6 months'), ('m12', '12 months'), ('lifetime', 'Lifetime')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='moduleseason',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='accounts.module'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='season',
            field=models.ForeignKey(blank=True, help_text='If set, entitlement only applies to that content season.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='accounts.moduleseason'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['user', 'season'], name='idx_ent_user_season'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(fields=('user', 'module', 'season', 'plan', 'starts_at'), name='uniq_ent_user_scope_plan_start'),
        ),
        migrations.AddIndex(
            model_name='moduleseason',
            index=models.Index(fields=['module', 'season_number'], name='idx_module_season_num'),
        ),
        migrations.AddConstraint(
            model_name='moduleseason',
            constraint=models.UniqueConstraint(fields=('module', 'season_number'), name='uniq_module_season_number'),
        ),
    ]
