# Generated by Django 6.0 on 2026-01-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_moduleseason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
