# Generated by Django 6.0 on 2026-01-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='learning_days',
            new_name='active_days',
        ),
        migrations.AddField(
            model_name='userdata',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
