# Generated by Django 6.0 on 2026-01-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_learning_days_userdata_active_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActiveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_day_entries', to='accounts.userdata')),
            ],
            options={
                'indexes': [models.Index(fields=['user_data', 'date'], name='accounts_us_user_da_defd53_idx'), models.Index(fields=['date'], name='accounts_us_date_dc963d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_data', 'date'), name='uniq_user_active_day_user_date')],
            },
        ),
    ]
