# Generated by Django 6.0 on 2026-04-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayWebsitePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_order_no', models.CharField(help_text='Merchant-generated unique order number.', max_length=64, unique=True)),
                ('subject', models.CharField(help_text='Payment subject shown to the customer and Alipay.', max_length=256)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total payment amount in the configured merchant currency.', max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('closed', 'Closed')], db_index=True, default='created', help_text='Current payment lifecycle status.', max_length=16)),
                ('alipay_trade_no', models.CharField(blank=True, db_index=True, default='', help_text='Alipay trade number returned by Alipay after payment creation or completion.', max_length=64)),
                ('raw_notify_payload', models.JSONField(blank=True, help_text='Raw notify payload received from Alipay, if available.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when the payment was confirmed as paid.', null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_alipay_status_created')],
            },
        ),
    ]
