# Generated by Django 6.0 on 2026-04-12 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alipaywebsitepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGrantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial_7d', 'Trial (7 days)'), ('m1', '1 month'), ('m3', '3 months'), ('m6', '6 months'), ('m12', '12 months'), ('lifetime', 'Lifetime')], help_text='Entitlement duration plan to grant after successful payment.', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current processing state of the entitlement grant task.', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of consumer attempts that have processed this task.')),
                ('last_error', models.TextField(blank=True, default='', help_text='Last processing error message, if any.')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when the task was successfully processed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, help_text='Target module for the entitlement, if the payment is module-scoped.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_grant_tasks', to='accounts.module')),
                ('payment', models.ForeignKey(help_text='Payment record that triggered this entitlement grant task.', on_delete=django.db.models.deletion.CASCADE, related_name='grant_tasks', to='accounts.alipaywebsitepayment')),
                ('season', models.ForeignKey(blank=True, help_text='Target season for the entitlement, if the payment is season-scoped.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_grant_tasks', to='accounts.moduleseason')),
                ('user', models.ForeignKey(help_text='User who should receive the entitlement after successful payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_grant_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_paygrant_status_created'), models.Index(fields=['user', 'status'], name='idx_paygrant_user_status')],
                'constraints': [models.UniqueConstraint(fields=('payment', 'user', 'module', 'season', 'plan'), name='uniq_paygrant_payment_scope_plan')],
            },
        ),
    ]
