# Generated by Django 6.0 on 2026-08-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_schreiben_guide_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='plan',
            field=models.CharField(choices=[('trial_7d', 'Trial (7 days)'), ('m1', '30 days'), ('m2', '60 days'), ('m3', '90 days'), ('m6', '6 months'), ('m12', '12 months'), ('lifetime', 'Lifetime')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentgranttask',
            name='plan',
            field=models.CharField(choices=[('trial_7d', 'Trial (7 days)'), ('m1', '30 days'), ('m2', '60 days'), ('m3', '90 days'), ('m6', '6 months'), ('m12', '12 months'), ('lifetime', 'Lifetime')], help_text='Entitlement duration plan to grant after successful payment.', max_length=16),
        ),
        migrations.AlterField(
            model_name='purchaseoffer',
            name='plan',
            field=models.CharField(choices=[('trial_7d', 'Trial (7 days)'), ('m1', '30 days'), ('m2', '60 days'), ('m3', '90 days'), ('m6', '6 months'), ('m12', '12 months'), ('lifetime', 'Lifetime')], db_index=True, max_length=16),
        ),
        migrations.AddConstraint(
            model_name='alipaywebsitepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('alipay_trade_no', ''), _negated=True), fields=('alipay_trade_no',), name='uniq_nonblank_alipay_trade_no'),
        ),
        migrations.AddConstraint(
            model_name='purchaseoffer',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__gt', 0)), name='purchase_offer_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseoffer',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'CNY')), name='purchase_offer_currency_cny'),
        ),
    ]
