# Generated by Django 6.0 on 2026-09-01 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_activation_code_remark_ciphertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('organization_name', models.CharField(blank=True, default='', max_length=128)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCodeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('code_ciphertext', models.TextField(blank=True, default='')),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_stackable', models.BooleanField(default=False)),
                ('coupon_valid_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_codes', to='accounts.module')),
                ('applicable_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_codes', to='accounts.purchaseoffer')),
                ('applicable_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_codes', to='accounts.moduleseason')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_codes', to='accounts.promotioncampaign')),
                ('consumed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_promotion_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_stackable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='available', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_coupons', to='accounts.module')),
                ('applicable_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_coupons', to='accounts.purchaseoffer')),
                ('applicable_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_coupons', to='accounts.moduleseason')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='accounts.promotioncampaign')),
                ('promotion_code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon', to='accounts.promotioncoderecord')),
                ('reserved_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_coupon', to='accounts.alipaywebsitepayment')),
                ('used_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_coupon', to='accounts.alipaywebsitepayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDiscountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('automatic_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promotion_discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('applied', 'Applied'), ('released', 'Released'), ('refunded', 'Refunded')], db_index=True, default='reserved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_discount_applications', to='accounts.purchaseoffer')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='discount_application', to='accounts.alipaywebsitepayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_purchases', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_applications', to='accounts.promotioncampaign')),
                ('promotion_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_applications', to='accounts.promotioncoderecord')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_applications', to='accounts.usercoupon')),
            ],
        ),
        migrations.AddIndex(
            model_name='promotioncoderecord',
            index=models.Index(fields=['campaign', 'status', 'consumed_at'], name='idx_promo_campaign_use'),
        ),
        migrations.AddIndex(
            model_name='promotioncoderecord',
            index=models.Index(fields=['consumed_by_user', 'status'], name='idx_promo_user_status'),
        ),
        migrations.AddConstraint(
            model_name='promotioncoderecord',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gt', 0)), name='promo_discount_positive'),
        ),
        migrations.AddConstraint(
            model_name='promotioncoderecord',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_order_amount__gte', 0)), name='promo_minimum_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='promotioncoderecord',
            constraint=models.CheckConstraint(condition=models.Q(('coupon_valid_days__gt', 0)), name='promo_valid_days_positive'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='idx_coupon_user_available'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['campaign', 'status', 'used_at'], name='idx_coupon_campaign_use'),
        ),
        migrations.AddConstraint(
            model_name='usercoupon',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gt', 0)), name='coupon_discount_positive'),
        ),
        migrations.AddConstraint(
            model_name='usercoupon',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_order_amount__gte', 0)), name='coupon_minimum_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='paymentdiscountapplication',
            index=models.Index(fields=['campaign', 'status', 'applied_at'], name='idx_discount_campaign_paid'),
        ),
        migrations.AddIndex(
            model_name='paymentdiscountapplication',
            index=models.Index(fields=['user', 'status'], name='idx_discount_user_status'),
        ),
        migrations.AddConstraint(
            model_name='paymentdiscountapplication',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='discount_original_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentdiscountapplication',
            constraint=models.CheckConstraint(condition=models.Q(('automatic_discount_amount__gte', 0)), name='discount_auto_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentdiscountapplication',
            constraint=models.CheckConstraint(condition=models.Q(('promotion_discount_amount__gt', 0)), name='discount_promo_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentdiscountapplication',
            constraint=models.CheckConstraint(condition=models.Q(('final_amount__gt', 0)), name='discount_final_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentdiscountapplication',
            constraint=models.CheckConstraint(condition=models.Q(('final_amount__lte', models.F('original_amount'))), name='discount_final_lte_original'),
        ),
    ]
