[project]
name = "frau-liu-learn-german"
version = "0.1.0"
description = "Add your description here"
readme = "local-docs/project-readme.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "celery[redis]>=5.6.3",
    "cryptography>=45.0.7",
    "django>=4.2.27",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.12.0",
    "django-filter>=25.2",
    "django-redis>=6.0.0",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "djangorestframework-stubs>=3.16.7",
    "drf-spectacular>=0.29.0",
    "gunicorn>=25.0.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pandas-stubs~=2.3.3",
    "psycopg[binary]>=3.2.13",
]
