from __future__ import annotations

from collections import Counter
from pathlib import Path
import re
from typing import Any, Callable
import unicodedata
from urllib.parse import quote, unquote, urlparse

from django.apps import apps
from django.core.management.base import BaseCommand, CommandParser
from django.db import transaction

from apps.learning_by_video.management.commands.import_videos import _normalize_media_key
from apps.learning_by_video.management.commands.fill_selected_from_xlsx import _resolve_video as _resolve_video_from_xlsx
from apps.learning_by_video.management.commands.fill_selected_from_xlsx import _sheet as _xlsx_sheet
from apps.learning_by_video.management.commands.import_videos import (
    COL_TITLE,
    COL_TITLE_ORIG,
    COL_TITLE_ZH,
    SHEET_NAME as SHEET_VIDEO_DESCRIPTION,
)
from apps.learning_by_video.models import Video

SCIENCE_SEASON1_VIDEO_DIR_REL = Path("frontend/public/resources/ScienceSeason1/learning_by_video_video")
SCIENCE_SEASON1_COVER_DIR_REL = Path("frontend/public/resources/ScienceSeason1/learning_by_video_cover_letters")
SCIENCE_SEASON1_VIDEO_URL_PREFIX = "/resources/ScienceSeason1/learning_by_video_video"
SCIENCE_SEASON1_COVER_URL_PREFIX = "/resources/ScienceSeason1/learning_by_video_cover_letters"
XLSX_METADATA_DIRS_REL = [
    Path("apps/learning_by_video/data/raw"),
    Path("apps/learning_by_video/data/processed"),
]
_EPISODE_SUFFIX_RE = re.compile(r"[（(]\s*(\d+)\s*[)）]\s*$")


def _project_root() -> Path:
    app_config = apps.get_app_config("learning_by_video")
    # app path: <root>/apps/learning_by_video
    return Path(app_config.path).resolve().parents[1]


def _resolve_resource_folder(root: Path, raw_value: str, default_rel: Path) -> Path:
    value = str(raw_value or "").strip()
    if not value:
        return (root / default_rel).resolve()
    p = Path(value).expanduser()
    if not p.is_absolute():
        p = root / p
    return p.resolve()


def _derive_public_url_prefix(*, root: Path, folder: Path, fallback: str) -> str:
    public_root = (root / "frontend" / "public").resolve()
    try:
        rel = folder.resolve().relative_to(public_root)
    except ValueError:
        return fallback
    parts = [part for part in rel.parts if part]
    return "/" + "/".join(parts) if parts else fallback


def _normalize_ascii_media_key(text: str) -> str:
    """
    ASCII-folded media key used to match normalized filenames generated by scripts.
    Example: "München" -> "munchen", "Straße" -> "strasse".
    """
    s = str(text or "")
    s = s.replace("ß", "ss").replace("ẞ", "SS")
    s = unicodedata.normalize("NFKD", s)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    return "".join(ch.lower() for ch in s if ch.isalnum())


def _build_file_map(
    folder: Path,
    allowed_exts: set[str] | None = None,
    ext_preference: dict[str, int] | None = None,
    key_normalizer: Callable[[str], str] = _normalize_media_key,
) -> dict[str, str]:
    out: dict[str, str] = {}
    if not folder.exists():
        return out

    for p in sorted(folder.iterdir(), key=lambda x: x.name.lower()):
        if not p.is_file():
            continue
        if allowed_exts is not None and p.suffix.lower() not in allowed_exts:
            continue
        # Ignore HLS internals when mapping "playable source" filenames.
        # We only want top-level assets like *.m3u8 / full *.mp4.
        stem_lower = p.stem.lower()
        if stem_lower.endswith("-init"):
            continue
        if re.search(r"-\d{3,4}$", stem_lower):
            continue
        key = key_normalizer(p.stem)
        if not key:
            continue
        if key not in out:
            out[key] = p.name
            continue
        if ext_preference is not None:
            new_ext = p.suffix.lower()
            old_ext = Path(out[key]).suffix.lower()
            if ext_preference.get(new_ext, 99) < ext_preference.get(old_ext, 99):
                out[key] = p.name
    return out


def _find_filename(
    title: str,
    file_map: dict[str, str],
    file_map_ascii: dict[str, str] | None = None,
) -> str:
    key = _normalize_media_key(title)
    if not key:
        key_ascii = _normalize_ascii_media_key(title)
        if file_map_ascii and key_ascii and key_ascii in file_map_ascii:
            return file_map_ascii[key_ascii]
        return ""
    if key in file_map:
        return file_map[key]
    key_ascii = _normalize_ascii_media_key(title)
    if file_map_ascii and key_ascii and key_ascii in file_map_ascii:
        return file_map_ascii[key_ascii]

    def _trailing_number(value: str) -> str:
        m = re.search(r"(\d+)$", value or "")
        return m.group(1) if m else ""

    requested_num = _trailing_number(key)

    best = ""
    best_len = 0
    for k, filename in file_map.items():
        existing_num = _trailing_number(k)
        if requested_num and existing_num and requested_num != existing_num:
            continue
        if k in key or key in k:
            if len(k) > best_len:
                best = filename
                best_len = len(k)
    if best:
        return best

    if file_map_ascii and key_ascii:
        requested_num_ascii = _trailing_number(key_ascii)
        for k, filename in file_map_ascii.items():
            existing_num_ascii = _trailing_number(k)
            if requested_num_ascii and existing_num_ascii and requested_num_ascii != existing_num_ascii:
                continue
            if k in key_ascii or key_ascii in k:
                if len(k) > best_len:
                    best = filename
                    best_len = len(k)
    return best


def _collect_title_hints_from_xlsx(root: Path) -> dict[int, list[str]]:
    """
    Build video_id -> title hints from xlsx metadata (raw + processed).
    Includes 中文标题 / 原标题 / 标题.
    """
    hints: dict[int, list[str]] = {}
    seen_files: set[Path] = set()

    def _add_hint(video_id: int, value: str) -> None:
        text = str(value or "").strip()
        if not text:
            return
        arr = hints.setdefault(video_id, [])
        if text not in arr:
            arr.append(text)

    for rel in XLSX_METADATA_DIRS_REL:
        d = root / rel
        if not d.exists():
            continue
        for p in sorted(d.glob("*.xlsx")):
            rp = p.resolve()
            if rp in seen_files:
                continue
            seen_files.add(rp)
            try:
                video = _resolve_video_from_xlsx(p)
            except Exception:
                continue
            if video is None:
                continue
            try:
                df = _xlsx_sheet(p, SHEET_VIDEO_DESCRIPTION)
            except Exception:
                continue
            if df.shape[0] < 1:
                continue
            row = df.iloc[0]
            for col in (COL_TITLE_ORIG, COL_TITLE_ZH, COL_TITLE):
                _add_hint(video.id, row.get(col, ""))

    return hints


def _url_bucket(raw_url: str) -> str:
    s = (raw_url or "").strip()
    if not s:
        return "empty"
    if s.startswith(("http://", "https://")):
        parsed = urlparse(s)
        host = parsed.netloc or "unknown-host"
        return f"remote:{host}"
    if s.startswith("/"):
        parts = [x for x in s.split("/") if x]
        if len(parts) >= 2:
            return f"local:/{parts[0]}/{parts[1]}"
        return "local:/"
    return "relative"


def _build_media_url(prefix: str, filename: str) -> str:
    # Encode path segment so reserved chars like '?' don't break URLs.
    return f"{prefix}/{quote(filename, safe='')}"


def _local_url_points_to_existing_file(*, raw_url: str, prefix: str, folder: Path) -> bool:
    s = (raw_url or "").strip()
    if not s or not s.startswith(prefix + "/"):
        return False
    name = s[len(prefix) + 1 :]
    name = name.split("?", 1)[0].split("#", 1)[0]
    if not name:
        return False
    filename = unquote(name)
    return (folder / filename).exists()


def _has_unsafe_filename_chars(url: str) -> bool:
    s = (url or "").strip()
    if not s:
        return False
    if not s.startswith("/"):
        return False
    name = s.rsplit("/", 1)[-1]
    # If raw reserved chars are present, browser/server may parse URL incorrectly.
    return any(ch in name for ch in ("?", "#", " "))


def _has_unsafe_hls_name(filename: str) -> bool:
    """
    HLS playlist/segment URI handling is fragile when stem contains '?' or '#'.
    """
    s = (filename or "").strip()
    return ("?" in s) or ("#" in s)


def _sanitize_stem_for_alias(stem: str) -> str:
    s = unicodedata.normalize("NFKD", stem or "")
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = s.replace("?", "_").replace("#", "_")
    s = re.sub(r"\s+", "_", s)
    s = re.sub(r"[^A-Za-z0-9._-]+", "_", s)
    s = re.sub(r"_+", "_", s).strip("._")
    return s or "media"


def _needs_safe_alias(filename: str) -> bool:
    s = (filename or "").strip()
    if not s:
        return False
    # Keep URL/file-system handling robust across platforms and unicode normalization.
    if any(ch in s for ch in ("?", "#", "%", " ")):
        return True
    try:
        s.encode("ascii")
    except UnicodeEncodeError:
        return True
    return False


def _ensure_safe_alias_filename(
    *,
    folder: Path,
    filename: str,
    mode: str,
    create_missing_alias: bool = False,
) -> str:
    """
    Return a safe filename for URL usage.
    If safe filename already exists, reuse it.
    In apply mode, can optionally rename source file to safe filename.
    """
    src_name = (filename or "").strip()
    if not src_name:
        return src_name

    # If file name is URL-safe and ASCII-only, keep as is.
    if not _needs_safe_alias(src_name):
        return src_name

    stem = _sanitize_stem_for_alias(Path(src_name).stem)
    suffix = Path(src_name).suffix
    alias_name = f"{stem}{suffix}"
    alias = folder / alias_name

    if alias.exists():
        return alias_name

    if not create_missing_alias:
        return src_name
    if mode != "apply":
        return src_name

    src = folder / src_name
    if not src.exists() or not src.is_file():
        return src_name

    # Avoid creating "safe alias" for HLS playlist only, because playlist internals
    # may still reference unsafe segment names. Those should come from normalized slicing.
    if src.suffix.lower() == ".m3u8":
        return src_name

    try:
        src.rename(alias)
        return alias_name
    except OSError:
        # Keep source filename when rename is not possible.
        pass

    return src_name


def _expand_title_candidates(text: str) -> list[str]:
    """
    Build matching candidates from a title:
    - original full title
    - segment before/after colon-like separators
    """
    s = str(text or "").strip()
    if not s:
        return []
    out: list[str] = [s]
    m = _EPISODE_SUFFIX_RE.search(s)
    episode_no = m.group(1) if m else ""
    for sep in (":", "："):
        if sep in s:
            left, right = s.split(sep, 1)
            left = left.strip()
            right = right.strip()
            if left and episode_no and not _EPISODE_SUFFIX_RE.search(left):
                c1 = f"{left} ({episode_no})"
                c2 = f"{left}（{episode_no}）"
                if c1 not in out:
                    out.append(c1)
                if c2 not in out:
                    out.append(c2)
            if left and left not in out:
                out.append(left)
            if right and right not in out:
                out.append(right)
    return out


def _get_season(module_key: str, season_number: int):
    Module = apps.get_model("accounts", "Module")
    ModuleSeason = apps.get_model("accounts", "ModuleSeason")
    module = Module.objects.filter(key=module_key, is_active=True).first()
    if not module:
        return None
    return ModuleSeason.objects.filter(module=module, season_number=season_number).first()


class Command(BaseCommand):
    help = (
        "Inspect current video_url/cover_letter_url patterns, and set local resource URLs for videos "
        "based on title->filename matching. Supports validate/apply. Can also ensure target season restriction."
    )

    def add_arguments(self, parser: CommandParser) -> None:
        parser.add_argument("--mode", choices=["validate", "apply"], default="validate")
        parser.add_argument(
            "--only-missing",
            action="store_true",
            default=True,
            help="Only fill when video_url/cover_letter_url is empty (default).",
        )
        parser.add_argument(
            "--all",
            action="store_true",
            help="Process all videos (override --only-missing).",
        )
        parser.add_argument(
            "--empty-only",
            action="store_true",
            help="When used with --only-missing, fill ONLY empty URL fields and never touch existing URLs.",
        )
        parser.add_argument(
            "--video-id",
            type=int,
            action="append",
            default=[],
            help="Optional specific video IDs (can be repeated).",
        )
        parser.add_argument(
            "--exclude-video-id",
            type=int,
            action="append",
            default=[],
            help="Optional video IDs to skip (can be repeated).",
        )
        parser.add_argument("--module-key", default="learning_by_video")
        parser.add_argument("--season-number", type=int, default=1)
        parser.add_argument(
            "--video-dir",
            default="",
            help=(
                "Video resource folder to scan. Defaults to "
                "frontend/public/resources/ScienceSeason1/learning_by_video_video."
            ),
        )
        parser.add_argument(
            "--cover-dir",
            default="",
            help=(
                "Cover resource folder to scan. Defaults to "
                "frontend/public/resources/ScienceSeason1/learning_by_video_cover_letters."
            ),
        )
        parser.add_argument(
            "--video-url-prefix",
            default="",
            help="Optional URL prefix for generated video_url values. Auto-derived from --video-dir when omitted.",
        )
        parser.add_argument(
            "--cover-url-prefix",
            default="",
            help=(
                "Optional URL prefix for generated cover_letter_url values. "
                "Auto-derived from --cover-dir when omitted."
            ),
        )
        parser.add_argument(
            "--ensure-season",
            action="store_true",
            default=True,
            help="Ensure videos have season set (default: on).",
        )
        parser.add_argument(
            "--no-ensure-season",
            action="store_true",
            help="Do not change season.",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        mode = str(options["mode"])
        only_missing = bool(options.get("only_missing", True))
        if options.get("all"):
            only_missing = False
        empty_only = bool(options.get("empty_only", False))

        ensure_season = bool(options.get("ensure_season", True))
        if options.get("no_ensure_season"):
            ensure_season = False

        video_ids: list[int] = list(options.get("video_id") or [])
        exclude_video_ids: set[int] = set(options.get("exclude_video_id") or [])
        module_key = str(options.get("module_key") or "learning_by_video")
        season_number = int(options.get("season_number") or 1)

        root = _project_root()
        video_dir = _resolve_resource_folder(
            root,
            str(options.get("video_dir") or ""),
            SCIENCE_SEASON1_VIDEO_DIR_REL,
        )
        cover_dir = _resolve_resource_folder(
            root,
            str(options.get("cover_dir") or ""),
            SCIENCE_SEASON1_COVER_DIR_REL,
        )
        video_url_prefix = str(options.get("video_url_prefix") or "").strip() or _derive_public_url_prefix(
            root=root,
            folder=video_dir,
            fallback=SCIENCE_SEASON1_VIDEO_URL_PREFIX,
        )
        cover_url_prefix = str(options.get("cover_url_prefix") or "").strip() or _derive_public_url_prefix(
            root=root,
            folder=cover_dir,
            fallback=SCIENCE_SEASON1_COVER_URL_PREFIX,
        )

        cover_map = _build_file_map(cover_dir, allowed_exts=None)
        cover_map_ascii = _build_file_map(
            cover_dir,
            allowed_exts=None,
            key_normalizer=_normalize_ascii_media_key,
        )
        video_map = _build_file_map(
            video_dir,
            allowed_exts={".mp4", ".m3u8", ".m4v", ".mov", ".webm"},
            # Keep URLs in HLS format by default when both m3u8 and mp4 exist.
            ext_preference={".m3u8": 0, ".mp4": 1, ".m4v": 2, ".mov": 3, ".webm": 4},
        )
        video_map_ascii = _build_file_map(
            video_dir,
            allowed_exts={".mp4", ".m3u8", ".m4v", ".mov", ".webm"},
            ext_preference={".m3u8": 0, ".mp4": 1, ".m4v": 2, ".mov": 3, ".webm": 4},
            key_normalizer=_normalize_ascii_media_key,
        )
        video_map_mp4 = _build_file_map(
            video_dir,
            allowed_exts={".mp4"},
            ext_preference={".mp4": 0},
        )
        video_map_mp4_ascii = _build_file_map(
            video_dir,
            allowed_exts={".mp4"},
            ext_preference={".mp4": 0},
            key_normalizer=_normalize_ascii_media_key,
        )
        video_map_hls = _build_file_map(
            video_dir,
            allowed_exts={".m3u8"},
            ext_preference={".m3u8": 0},
        )
        video_map_hls_ascii = _build_file_map(
            video_dir,
            allowed_exts={".m3u8"},
            ext_preference={".m3u8": 0},
            key_normalizer=_normalize_ascii_media_key,
        )

        qs = Video.objects.all().order_by("id")
        if video_ids:
            qs = qs.filter(id__in=video_ids)
        if exclude_video_ids:
            qs = qs.exclude(id__in=exclude_video_ids)
        target_season = _get_season(module_key=module_key, season_number=season_number)
        if target_season is None and not video_ids:
            raise ValueError(
                f"Target season not found for module={module_key!r}, season_number={season_number}. "
                "Refusing to scan all videos without an explicit video scope."
            )
        if target_season is not None:
            qs = qs.filter(season_id=target_season.id)
        videos = list(qs)
        title_hints = _collect_title_hints_from_xlsx(root)

        url_stats = Counter(_url_bucket(v.video_url) for v in videos)
        cover_stats = Counter(_url_bucket(v.cover_letter_url) for v in videos)

        updated = 0
        season_updated = 0
        unresolved: list[str] = []

        with transaction.atomic():
            for v in videos:
                changed_fields: list[str] = []
                picked_video_filename = ""
                has_existing_video_file = _local_url_points_to_existing_file(
                    raw_url=v.video_url,
                    prefix=video_url_prefix,
                    folder=video_dir,
                )
                has_existing_cover_file = _local_url_points_to_existing_file(
                    raw_url=v.cover_letter_url,
                    prefix=cover_url_prefix,
                    folder=cover_dir,
                )

                is_video_empty = not (v.video_url or "").strip()
                is_cover_empty = not (v.cover_letter_url or "").strip()
                if only_missing and empty_only:
                    need_video_url = is_video_empty
                    need_cover_url = is_cover_empty
                else:
                    need_video_url = (
                        (not only_missing)
                        or is_video_empty
                        or (_has_unsafe_filename_chars(v.video_url) and not has_existing_video_file)
                    )
                    need_cover_url = (
                        (not only_missing)
                        or is_cover_empty
                        or (_has_unsafe_filename_chars(v.cover_letter_url) and not has_existing_cover_file)
                    )

                if need_video_url:
                    video_filename = ""
                    candidate_titles: list[str] = []
                    for t in [v.title] + title_hints.get(v.id, []):
                        for x in _expand_title_candidates(t):
                            if x not in candidate_titles:
                                candidate_titles.append(x)
                    for t in candidate_titles:
                        video_filename = _find_filename(
                            t,
                            video_map,
                            file_map_ascii=video_map_ascii,
                        )
                        if video_filename:
                            # If the exact-title match landed on a raw MOV while an
                            # ASCII-normalized HLS playlist also exists, prefer HLS.
                            if Path(video_filename).suffix.lower() != ".m3u8":
                                hls_filename = _find_filename(
                                    t,
                                    video_map_hls,
                                    file_map_ascii=video_map_hls_ascii,
                                )
                                if hls_filename:
                                    video_filename = hls_filename
                            break
                    # If chosen HLS filename is unsafe (e.g. contains '?'),
                    # prefer a safe-named HLS alias when present;
                    # otherwise fallback to MP4 to avoid broken segment URI parsing.
                    if video_filename and Path(video_filename).suffix.lower() == ".m3u8" and _has_unsafe_hls_name(video_filename):
                        safe_hls_alias = f"{_sanitize_stem_for_alias(Path(video_filename).stem)}.m3u8"
                        if (video_dir / safe_hls_alias).exists():
                            video_filename = safe_hls_alias
                        else:
                            key = _normalize_media_key(Path(video_filename).stem)
                            mp4_filename = video_map_mp4.get(key, "")
                            if not mp4_filename:
                                key_ascii = _normalize_ascii_media_key(Path(video_filename).stem)
                                mp4_filename = video_map_mp4_ascii.get(key_ascii, "")
                            if mp4_filename:
                                video_filename = mp4_filename
                    if video_filename:
                        video_filename = _ensure_safe_alias_filename(
                            folder=video_dir,
                            filename=video_filename,
                            mode=mode,
                            create_missing_alias=True,
                        )
                        picked_video_filename = video_filename
                        new_video_url = _build_media_url(
                            video_url_prefix,
                            video_filename,
                        )
                        if v.video_url != new_video_url:
                            v.video_url = new_video_url
                            changed_fields.append("video_url")
                    else:
                        unresolved.append(
                            f"[video_url] id={v.id} title={v.title} | no matching file in {video_dir}"
                        )

                if need_cover_url:
                    # Prefer exact same stem as picked video file.
                    cover_filename = ""
                    if picked_video_filename:
                        same_stem_key = _normalize_media_key(Path(picked_video_filename).stem)
                        cover_filename = cover_map.get(same_stem_key, "")
                        if not cover_filename:
                            same_stem_key_ascii = _normalize_ascii_media_key(
                                Path(picked_video_filename).stem
                            )
                            cover_filename = cover_map_ascii.get(same_stem_key_ascii, "")
                    if not cover_filename:
                        candidate_titles = []
                        for t in [v.title] + title_hints.get(v.id, []):
                            for x in _expand_title_candidates(t):
                                if x not in candidate_titles:
                                    candidate_titles.append(x)
                        for t in candidate_titles:
                            cover_filename = _find_filename(
                                t,
                                cover_map,
                                file_map_ascii=cover_map_ascii,
                            )
                            if cover_filename:
                                break
                    if cover_filename:
                        cover_filename = _ensure_safe_alias_filename(
                            folder=cover_dir,
                            filename=cover_filename,
                            mode=mode,
                            create_missing_alias=True,
                        )
                        new_cover_url = _build_media_url(
                            cover_url_prefix,
                            cover_filename,
                        )
                        if v.cover_letter_url != new_cover_url:
                            v.cover_letter_url = new_cover_url
                            changed_fields.append("cover_letter_url")
                    else:
                        unresolved.append(
                            f"[cover_letter_url] id={v.id} title={v.title} | no matching file in {cover_dir}"
                        )

                if ensure_season and target_season and v.season_id is None:
                    # For this batch, add season restriction only when missing.
                    v.season = target_season
                    changed_fields.append("season")
                    season_updated += 1

                if changed_fields:
                    v.save(update_fields=sorted(set(changed_fields)))
                    updated += 1

            if mode == "validate":
                transaction.set_rollback(True)

        self.stdout.write(f"mode={mode}")
        self.stdout.write(f"videos scanned: {len(videos)}")
        self.stdout.write(f"target season id: {getattr(target_season, 'id', None)}")
        self.stdout.write(f"video url prefix: {video_url_prefix}")
        self.stdout.write(f"cover url prefix: {cover_url_prefix}")
        self.stdout.write(f"resource dir video exists: {video_dir.exists()} | files indexed={len(video_map)}")
        self.stdout.write(f"resource dir cover exists: {cover_dir.exists()} | files indexed={len(cover_map)}")
        self.stdout.write(f"videos updated: {updated}")
        self.stdout.write(f"season updated: {season_updated}")

        self.stdout.write("\n=== video_url location stats ===")
        for k, c in sorted(url_stats.items(), key=lambda x: (-x[1], x[0])):
            self.stdout.write(f"{k}: {c}")

        self.stdout.write("\n=== cover_letter_url location stats ===")
        for k, c in sorted(cover_stats.items(), key=lambda x: (-x[1], x[0])):
            self.stdout.write(f"{k}: {c}")

        self.stdout.write("\n=== unresolved (manual check) ===")
        if not unresolved:
            self.stdout.write("none")
        else:
            for line in unresolved:
                self.stdout.write(line)

        if mode == "validate":
            self.stdout.write(self.style.WARNING("\nvalidate mode: rolled back"))
        else:
            self.stdout.write(self.style.SUCCESS("\napply mode: committed"))
