# Generated by Django 6.0 on 2025-12-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, default='de', max_length=8)),
                ('text', models.TextField()),
                ('normalized_text', models.TextField(db_index=True, editable=False)),
                ('level', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('similar_expressions', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('language', 'normalized_text'), name='uniq_expressiontext')],
            },
        ),
        migrations.CreateModel(
            name='SentenceText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, default='de', max_length=8)),
                ('text', models.TextField()),
                ('normalized_text', models.TextField(db_index=True, editable=False)),
                ('level', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('similar_expressions', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('language', 'normalized_text'), name='uniq_sentencetext')],
            },
        ),
        migrations.CreateModel(
            name='WordText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, default='de', max_length=8)),
                ('text', models.TextField()),
                ('normalized_text', models.TextField(db_index=True, editable=False)),
                ('level', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('similar_expressions', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lemma', models.CharField(blank=True, default='', max_length=128)),
                ('article', models.CharField(blank=True, choices=[('der', 'der'), ('die', 'die'), ('das', 'das'), ('plural', 'plural'), ('', '')], db_index=True, default='', max_length=10)),
                ('pos', models.CharField(blank=True, choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('PRON', 'Pronoun'), ('PREP', 'Preposition'), ('CONJ', 'Conjunction'), ('DET', 'Determiner'), ('PART', 'Particle'), ('INTJ', 'Interjection'), ('OTHER', 'Other')], db_index=True, default='', max_length=16)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('language', 'normalized_text', 'lemma', 'pos', 'article'), name='uniq_wordtext')],
            },
        ),
    ]
