# Generated by Django 6.0 on 2026-01-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtext',
            name='splittable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wordtext',
            name='article',
            field=models.CharField(blank=True, choices=[('der', 'der'), ('die', 'die'), ('das', 'das'), ('plural', 'plural'), ('', '')], db_index=True, default='', max_length=10, null=True),
        ),
    ]
