# Generated by Django 6.0 on 2026-01-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0003_expressiontext_prototype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressiontext',
            name='prototype',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
