# Generated by Django 6.0 on 2026-01-24 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_by_video', '0005_subtitle_external_id_subtitle_sub_v_extid'),
        ('lexicon', '0004_alter_expressiontext_prototype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpressionMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_state', models.CharField(choices=[('UNMARKED', 'Unmarked'), ('KNOWN', 'Known'), ('UNKNOWN', 'Unknown'), ('MIXED', 'Mixed')], db_index=True, default='UNMARKED', help_text='Aggregated knowledge state for this expression for the user.', max_length=16)),
                ('is_favorite', models.BooleanField(db_index=True, default=False, help_text='Whether the user favorited the expression.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_marks', to='lexicon.expressiontext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expression_marks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExpressionOccurrenceMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.CharField(choices=[('UNMARKED', 'Unmarked'), ('KNOWN', 'Known'), ('UNKNOWN', 'Unknown')], db_index=True, help_text='Knowledge state for this specific occurrence.', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_marks', to='learning_by_video.videoexpressionoccurrence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expression_occurrence_marks', to=settings.AUTH_USER_MODEL)),
                ('user_expression_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_marks', to='lexicon.userexpressionmark')),
            ],
        ),
        migrations.CreateModel(
            name='UserSentenceMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_state', models.CharField(choices=[('UNMARKED', 'Unmarked'), ('KNOWN', 'Known'), ('UNKNOWN', 'Unknown'), ('MIXED', 'Mixed')], db_index=True, default='UNMARKED', help_text='Aggregated knowledge state for this sentence for the user.', max_length=16)),
                ('is_favorite', models.BooleanField(db_index=True, default=False, help_text='Whether the user favorited the sentence.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_marks', to='lexicon.sentencetext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_marks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSentenceOccurrenceMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.CharField(choices=[('UNMARKED', 'Unmarked'), ('KNOWN', 'Known'), ('UNKNOWN', 'Unknown')], db_index=True, help_text='Knowledge state for this specific occurrence.', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_marks', to='learning_by_video.videosentenceoccurrence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_occurrence_marks', to=settings.AUTH_USER_MODEL)),
                ('user_sentence_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_marks', to='lexicon.usersentencemark')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_state', models.CharField(choices=[('UNMARKED', 'Unmarked'), ('KNOWN', 'Known'), ('UNKNOWN', 'Unknown'), ('MIXED', 'Mixed')], db_index=True, default='UNMARKED', help_text='Aggregated knowledge state for this word for the user.', max_length=16)),
                ('is_favorite', models.BooleanField(db_index=True, default=False, help_text='Whether the user favorited the word.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_marks', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_marks', to='lexicon.wordtext')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordOccurrenceMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.CharField(choices=[('UNMARKED', 'Unmarked'), ('KNOWN', 'Known'), ('UNKNOWN', 'Unknown')], db_index=True, help_text='Knowledge state for this specific occurrence.', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_marks', to='learning_by_video.videowordoccurrence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_occurrence_marks', to=settings.AUTH_USER_MODEL)),
                ('user_word_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_marks', to='lexicon.userwordmark')),
            ],
        ),
        migrations.AddIndex(
            model_name='userexpressionmark',
            index=models.Index(fields=['user', 'global_state'], name='idx_uem_u_gs'),
        ),
        migrations.AddIndex(
            model_name='userexpressionmark',
            index=models.Index(fields=['user', 'is_favorite'], name='idx_uem_u_f'),
        ),
        migrations.AddConstraint(
            model_name='userexpressionmark',
            constraint=models.UniqueConstraint(fields=('user', 'expression'), name='uniq_user_expression_mark'),
        ),
        migrations.AddIndex(
            model_name='userexpressionoccurrencemark',
            index=models.Index(fields=['user', 'knowledge'], name='idx_ueom_u_k'),
        ),
        migrations.AddIndex(
            model_name='userexpressionoccurrencemark',
            index=models.Index(fields=['user_expression_mark', 'knowledge'], name='idx_ueom_uem_k'),
        ),
        migrations.AddConstraint(
            model_name='userexpressionoccurrencemark',
            constraint=models.UniqueConstraint(fields=('user', 'occurrence'), name='uniq_user_expression_occurrence_mark'),
        ),
        migrations.AddIndex(
            model_name='usersentencemark',
            index=models.Index(fields=['user', 'global_state'], name='idx_usm_u_gs'),
        ),
        migrations.AddIndex(
            model_name='usersentencemark',
            index=models.Index(fields=['user', 'is_favorite'], name='idx_usm_u_f'),
        ),
        migrations.AddConstraint(
            model_name='usersentencemark',
            constraint=models.UniqueConstraint(fields=('user', 'sentence'), name='uniq_user_sentence_mark'),
        ),
        migrations.AddIndex(
            model_name='usersentenceoccurrencemark',
            index=models.Index(fields=['user', 'knowledge'], name='idx_usom_u_k'),
        ),
        migrations.AddIndex(
            model_name='usersentenceoccurrencemark',
            index=models.Index(fields=['user_sentence_mark', 'knowledge'], name='idx_usom_usm_k'),
        ),
        migrations.AddConstraint(
            model_name='usersentenceoccurrencemark',
            constraint=models.UniqueConstraint(fields=('user', 'occurrence'), name='uniq_user_sentence_occurrence_mark'),
        ),
        migrations.AddIndex(
            model_name='userwordmark',
            index=models.Index(fields=['user', 'global_state'], name='idx_uwm_u_gs'),
        ),
        migrations.AddIndex(
            model_name='userwordmark',
            index=models.Index(fields=['user', 'is_favorite'], name='idx_uwm_u_f'),
        ),
        migrations.AddConstraint(
            model_name='userwordmark',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='uniq_user_word_mark'),
        ),
        migrations.AddIndex(
            model_name='userwordoccurrencemark',
            index=models.Index(fields=['user', 'knowledge'], name='idx_uwom_u_k'),
        ),
        migrations.AddIndex(
            model_name='userwordoccurrencemark',
            index=models.Index(fields=['user_word_mark', 'knowledge'], name='idx_uwom_uwm_k'),
        ),
        migrations.AddConstraint(
            model_name='userwordoccurrencemark',
            constraint=models.UniqueConstraint(fields=('user', 'occurrence'), name='uniq_user_word_occurrence_mark'),
        ),
    ]
