# Generated by Django 6.0 on 2026-06-03 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClozeChoiceExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_with_placeholders', models.TextField(verbose_name='content with placeholders')),
                ('original_source_text', models.TextField(blank=True, default='', verbose_name='original source text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'cloze choice exercise',
                'verbose_name_plural': 'cloze choice exercises',
            },
        ),
        migrations.CreateModel(
            name='ClozeMatchingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_with_placeholders', models.TextField(verbose_name='content with placeholders')),
                ('original_source_text', models.TextField(blank=True, default='', verbose_name='original source text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'cloze matching exercise',
                'verbose_name_plural': 'cloze matching exercises',
            },
        ),
        migrations.CreateModel(
            name='ClozeChoiceBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_key', models.CharField(max_length=64, verbose_name='blank key')),
                ('blank_number', models.PositiveIntegerField(verbose_name='blank number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='exam_preparation.clozechoiceexercise', verbose_name='exercise')),
            ],
            options={
                'verbose_name': 'cloze choice blank',
                'verbose_name_plural': 'cloze choice blanks',
                'ordering': ['exercise_id', 'blank_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClozeChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=16, verbose_name='option key')),
                ('option_text', models.TextField(verbose_name='option text')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='is correct')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='explanation')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam_preparation.clozechoiceblank', verbose_name='blank')),
            ],
            options={
                'verbose_name': 'cloze choice option',
                'verbose_name_plural': 'cloze choice options',
                'ordering': ['blank_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClozeMatchingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=16, verbose_name='option key')),
                ('option_text', models.TextField(verbose_name='option text')),
                ('option_order', models.PositiveIntegerField(default=0, verbose_name='option order')),
                ('is_extra', models.BooleanField(db_index=True, default=False, verbose_name='is extra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam_preparation.clozematchingexercise', verbose_name='exercise')),
            ],
            options={
                'verbose_name': 'cloze matching option',
                'verbose_name_plural': 'cloze matching options',
                'ordering': ['exercise_id', 'option_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClozeMatchingBlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_key', models.CharField(max_length=64, verbose_name='blank key')),
                ('blank_number', models.PositiveIntegerField(verbose_name='blank number')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank_answers', to='exam_preparation.clozematchingexercise', verbose_name='exercise')),
                ('correct_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blank_answers', to='exam_preparation.clozematchingoption', verbose_name='correct option')),
            ],
            options={
                'verbose_name': 'cloze matching blank answer',
                'verbose_name_plural': 'cloze matching blank answers',
                'ordering': ['exercise_id', 'blank_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=8, verbose_name='level')),
                ('skill', models.CharField(choices=[('LISTENING', 'Listening'), ('READING', 'Reading'), ('SPRACHBAUSTEIN', 'Sprachbaustein'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], db_index=True, max_length=32, verbose_name='skill')),
                ('exercise_type', models.CharField(choices=[('LISTENING_CHOICE', 'Listening choice'), ('READING_TITLE_MATCHING', 'Reading title matching'), ('READING_UNDERSTANDING', 'Reading understanding'), ('READING_AD_MATCHING', 'Reading ad matching'), ('CLOZE_CHOICE', 'Cloze choice'), ('CLOZE_MATCHING', 'Cloze matching'), ('WRITING_PROMPT', 'Writing prompt'), ('SPEAKING_GAP_MATCHING', 'Speaking gap matching')], db_index=True, max_length=64, verbose_name='exercise type')),
                ('external_id', models.CharField(help_text='Human-readable exercise identifier used by editors and import files.', max_length=64, verbose_name='external ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('title_zh', models.CharField(blank=True, default='', max_length=255, verbose_name='Chinese title')),
                ('difficulty', models.CharField(blank=True, default='', max_length=32, verbose_name='difficulty')),
                ('is_real_exam', models.BooleanField(db_index=True, default=False, verbose_name='is real exam')),
                ('source_name', models.CharField(blank=True, default='', max_length=255, verbose_name='source name')),
                ('source_reference', models.CharField(blank=True, default='', max_length=255, verbose_name='source reference')),
                ('imported_from_file', models.CharField(blank=True, default='', max_length=255, verbose_name='imported from file')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='imported at')),
                ('creation_method', models.CharField(choices=[('manual', 'Manual'), ('xlsx_import', 'XLSX import'), ('script_import', 'Script import'), ('admin', 'Admin')], db_index=True, default='manual', max_length=32, verbose_name='creation method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'exercise base',
                'verbose_name_plural': 'exercise bases',
                'ordering': ['level', 'exercise_type', 'external_id', 'id'],
                'indexes': [models.Index(fields=['skill', 'level'], name='exam_prep_base_skill_lvl_idx'), models.Index(fields=['exercise_type', 'level'], name='exam_prep_base_type_lvl_idx'), models.Index(fields=['creation_method'], name='exam_prep_base_create_idx')],
                'constraints': [models.UniqueConstraint(fields=('level', 'exercise_type', 'external_id'), name='exam_prep_base_level_type_ext_uq')],
            },
        ),
        migrations.AddField(
            model_name='clozematchingexercise',
            name='exercise_base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloze_matching_exercise', to='exam_preparation.exercisebase', verbose_name='exercise base'),
        ),
        migrations.AddField(
            model_name='clozechoiceexercise',
            name='exercise_base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloze_choice_exercise', to='exam_preparation.exercisebase', verbose_name='exercise base'),
        ),
        migrations.CreateModel(
            name='ListeningExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_identifier', models.CharField(blank=True, default='', max_length=255, verbose_name='audio file identifier')),
                ('audio_file_url', models.CharField(blank=True, default='', max_length=500, verbose_name='audio file URL')),
                ('script', models.TextField(blank=True, default='', verbose_name='script')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listening_exercise', to='exam_preparation.exercisebase', verbose_name='exercise base')),
            ],
            options={
                'verbose_name': 'listening exercise',
                'verbose_name_plural': 'listening exercises',
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='question number')),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice')], max_length=32, verbose_name='question type')),
                ('question_text', models.TextField(verbose_name='question text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('listening_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam_preparation.listeningexercise', verbose_name='listening exercise')),
            ],
            options={
                'verbose_name': 'listening question',
                'verbose_name_plural': 'listening questions',
                'ordering': ['listening_exercise_id', 'question_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListeningAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=16, verbose_name='option key')),
                ('option_text', models.TextField(verbose_name='option text')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='is correct')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='explanation')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='exam_preparation.listeningquestion', verbose_name='question')),
            ],
            options={
                'verbose_name': 'listening answer option',
                'verbose_name_plural': 'listening answer options',
                'ordering': ['question_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingAdMatchingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, default='', verbose_name='instruction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_ad_matching_exercise', to='exam_preparation.exercisebase', verbose_name='exercise base')),
            ],
            options={
                'verbose_name': 'reading ad matching exercise',
                'verbose_name_plural': 'reading ad matching exercises',
            },
        ),
        migrations.CreateModel(
            name='ReadingAdMatchingAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_key', models.CharField(max_length=16, verbose_name='ad key')),
                ('ad_text_markdown', models.TextField(verbose_name='ad text markdown')),
                ('ad_order', models.PositiveIntegerField(default=0, verbose_name='ad order')),
                ('is_no_match_option', models.BooleanField(db_index=True, default=False, verbose_name='is no-match option')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='exam_preparation.readingadmatchingexercise', verbose_name='exercise')),
            ],
            options={
                'verbose_name': 'reading ad matching ad',
                'verbose_name_plural': 'reading ad matching ads',
                'ordering': ['exercise_id', 'ad_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingAdMatchingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField(verbose_name='item number')),
                ('item_text', models.TextField(verbose_name='item text')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('correct_ad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matched_items', to='exam_preparation.readingadmatchingad', verbose_name='correct ad')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exam_preparation.readingadmatchingexercise', verbose_name='exercise')),
            ],
            options={
                'verbose_name': 'reading ad matching item',
                'verbose_name_plural': 'reading ad matching items',
                'ordering': ['exercise_id', 'item_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTitleMatchingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, default='', verbose_name='instruction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_title_matching_exercise', to='exam_preparation.exercisebase', verbose_name='exercise base')),
            ],
            options={
                'verbose_name': 'reading title matching exercise',
                'verbose_name_plural': 'reading title matching exercises',
            },
        ),
        migrations.CreateModel(
            name='ReadingTitleMatchingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=16, verbose_name='option key')),
                ('option_text', models.TextField(verbose_name='option text')),
                ('option_order', models.PositiveIntegerField(default=0, verbose_name='option order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam_preparation.readingtitlematchingexercise', verbose_name='exercise')),
            ],
            options={
                'verbose_name': 'reading title matching option',
                'verbose_name_plural': 'reading title matching options',
                'ordering': ['exercise_id', 'option_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTitleMatchingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField(verbose_name='item number')),
                ('text', models.TextField(verbose_name='text')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exam_preparation.readingtitlematchingexercise', verbose_name='exercise')),
                ('correct_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matched_items', to='exam_preparation.readingtitlematchingoption', verbose_name='correct option')),
            ],
            options={
                'verbose_name': 'reading title matching item',
                'verbose_name_plural': 'reading title matching items',
                'ordering': ['exercise_id', 'item_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingUnderstandingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_markdown', models.TextField(verbose_name='text markdown')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_understanding_exercise', to='exam_preparation.exercisebase', verbose_name='exercise base')),
            ],
            options={
                'verbose_name': 'reading understanding exercise',
                'verbose_name_plural': 'reading understanding exercises',
            },
        ),
        migrations.CreateModel(
            name='ReadingUnderstandingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='question number')),
                ('question_text', models.TextField(verbose_name='question text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam_preparation.readingunderstandingexercise', verbose_name='exercise')),
            ],
            options={
                'verbose_name': 'reading understanding question',
                'verbose_name_plural': 'reading understanding questions',
                'ordering': ['exercise_id', 'question_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingUnderstandingAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=16, verbose_name='option key')),
                ('option_text', models.TextField(verbose_name='option text')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='is correct')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='explanation')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='exam_preparation.readingunderstandingquestion', verbose_name='question')),
            ],
            options={
                'verbose_name': 'reading understanding answer option',
                'verbose_name_plural': 'reading understanding answer options',
                'ordering': ['question_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingGapMatchingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_with_placeholders', models.TextField(verbose_name='content with placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_gap_matching_exercise', to='exam_preparation.exercisebase', verbose_name='exercise base')),
            ],
            options={
                'verbose_name': 'speaking gap matching exercise',
                'verbose_name_plural': 'speaking gap matching exercises',
            },
        ),
        migrations.CreateModel(
            name='SpeakingGapOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=16, verbose_name='option key')),
                ('option_text', models.TextField(verbose_name='option text')),
                ('option_order', models.PositiveIntegerField(default=0, verbose_name='option order')),
                ('is_extra', models.BooleanField(db_index=True, default=False, verbose_name='is extra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam_preparation.speakinggapmatchingexercise', verbose_name='exercise')),
            ],
            options={
                'verbose_name': 'speaking gap option',
                'verbose_name_plural': 'speaking gap options',
                'ordering': ['exercise_id', 'option_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingGapBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_key', models.CharField(max_length=64, verbose_name='blank key')),
                ('blank_number', models.PositiveIntegerField(verbose_name='blank number')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='exam_preparation.speakinggapmatchingexercise', verbose_name='exercise')),
                ('correct_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blanks', to='exam_preparation.speakinggapoption', verbose_name='correct option')),
            ],
            options={
                'verbose_name': 'speaking gap blank',
                'verbose_name_plural': 'speaking gap blanks',
                'ordering': ['exercise_id', 'blank_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='exam_preparation.exercisebase', verbose_name='exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_preparation_favorites', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user exercise favorite',
                'verbose_name_plural': 'user exercise favorites',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WritingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField(blank=True, default='', verbose_name='request text')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='time limit in minutes')),
                ('words_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='word limit')),
                ('task_text', models.TextField(blank=True, default='', verbose_name='task text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writing_exercise', to='exam_preparation.exercisebase', verbose_name='exercise base')),
            ],
            options={
                'verbose_name': 'writing exercise',
                'verbose_name_plural': 'writing exercises',
            },
        ),
        migrations.CreateModel(
            name='WritingExampleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text', models.TextField(verbose_name='example text')),
                ('label', models.CharField(blank=True, default='', max_length=64, verbose_name='label')),
                ('note', models.TextField(blank=True, default='', verbose_name='note')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('writing_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_texts', to='exam_preparation.writingexercise', verbose_name='writing exercise')),
            ],
            options={
                'verbose_name': 'writing example text',
                'verbose_name_plural': 'writing example texts',
                'ordering': ['writing_exercise_id', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='clozechoiceblank',
            constraint=models.UniqueConstraint(fields=('exercise', 'blank_key'), name='exam_prep_cc_blank_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='clozechoiceblank',
            constraint=models.UniqueConstraint(fields=('exercise', 'blank_number'), name='exam_prep_cc_blank_num_uq'),
        ),
        migrations.AddConstraint(
            model_name='clozechoiceoption',
            constraint=models.UniqueConstraint(fields=('blank', 'option_key'), name='exam_prep_cc_opt_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='clozematchingoption',
            constraint=models.UniqueConstraint(fields=('exercise', 'option_key'), name='exam_prep_cm_opt_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='clozematchingblankanswer',
            constraint=models.UniqueConstraint(fields=('exercise', 'blank_key'), name='exam_prep_cm_blank_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='clozematchingblankanswer',
            constraint=models.UniqueConstraint(fields=('exercise', 'blank_number'), name='exam_prep_cm_blank_num_uq'),
        ),
        migrations.AddConstraint(
            model_name='listeningquestion',
            constraint=models.UniqueConstraint(fields=('listening_exercise', 'question_number'), name='exam_prep_listen_q_num_uq'),
        ),
        migrations.AddConstraint(
            model_name='listeningansweroption',
            constraint=models.UniqueConstraint(fields=('question', 'option_key'), name='exam_prep_listen_opt_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='readingadmatchingad',
            constraint=models.UniqueConstraint(fields=('exercise', 'ad_key'), name='exam_prep_ram_ad_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='readingadmatchingitem',
            constraint=models.UniqueConstraint(fields=('exercise', 'item_number'), name='exam_prep_ram_item_num_uq'),
        ),
        migrations.AddConstraint(
            model_name='readingtitlematchingoption',
            constraint=models.UniqueConstraint(fields=('exercise', 'option_key'), name='exam_prep_rtm_opt_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='readingtitlematchingitem',
            constraint=models.UniqueConstraint(fields=('exercise', 'item_number'), name='exam_prep_rtm_item_num_uq'),
        ),
        migrations.AddConstraint(
            model_name='readingunderstandingquestion',
            constraint=models.UniqueConstraint(fields=('exercise', 'question_number'), name='exam_prep_ru_q_num_uq'),
        ),
        migrations.AddConstraint(
            model_name='readingunderstandingansweroption',
            constraint=models.UniqueConstraint(fields=('question', 'option_key'), name='exam_prep_ru_opt_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='speakinggapoption',
            constraint=models.UniqueConstraint(fields=('exercise', 'option_key'), name='exam_prep_sg_opt_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='speakinggapblank',
            constraint=models.UniqueConstraint(fields=('exercise', 'blank_key'), name='exam_prep_sg_blank_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='speakinggapblank',
            constraint=models.UniqueConstraint(fields=('exercise', 'blank_number'), name='exam_prep_sg_blank_num_uq'),
        ),
        migrations.AddConstraint(
            model_name='userexercisefavorite',
            constraint=models.UniqueConstraint(fields=('user', 'exercise'), name='exam_prep_user_exercise_fav_uq'),
        ),
        migrations.AddConstraint(
            model_name='writingexampletext',
            constraint=models.UniqueConstraint(fields=('writing_exercise', 'sort_order'), name='exam_prep_write_example_sort_uq'),
        ),
    ]
