# Generated by Django 6.0 on 2026-06-20 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_preparation', '0004_speakingpromptsegmentedexercise_speakingpromptsegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisebase',
            name='exercise_type',
            field=models.CharField(choices=[('LISTENING_CHOICE', 'Listening choice'), ('READING_TITLE_MATCHING', 'Reading title matching'), ('READING_UNDERSTANDING', 'Reading understanding'), ('READING_AD_MATCHING', 'Reading ad matching'), ('CLOZE_CHOICE', 'Cloze choice'), ('CLOZE_MATCHING', 'Cloze matching'), ('WRITING_PROMPT', 'Writing prompt'), ('SPEAKING_GAP_MATCHING', 'Speaking gap matching'), ('SPEAKING_PROMPT_SEGMENTED', 'Speaking prompt segmented')], db_index=True, max_length=64, verbose_name='exercise type'),
        ),
        migrations.CreateModel(
            name='UserClozeChoiceBlankState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(db_index=True, default=False, verbose_name='is favorited')),
                ('answer_payload', models.JSONField(blank=True, default=dict, verbose_name='answer payload')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='is correct')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='last answered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='exam_preparation.clozechoiceblank', verbose_name='blank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_preparation_cloze_choice_blank_states', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user cloze choice blank state',
                'verbose_name_plural': 'user cloze choice blank states',
                'ordering': ['-updated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'blank'), name='exam_prep_user_cc_blank_state_uq')],
            },
        ),
        migrations.CreateModel(
            name='UserClozeMatchingBlankState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(db_index=True, default=False, verbose_name='is favorited')),
                ('answer_payload', models.JSONField(blank=True, default=dict, verbose_name='answer payload')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='is correct')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='last answered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='exam_preparation.clozematchingblankanswer', verbose_name='blank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_preparation_cloze_matching_blank_states', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user cloze matching blank state',
                'verbose_name_plural': 'user cloze matching blank states',
                'ordering': ['-updated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'blank'), name='exam_prep_user_cm_blank_state_uq')],
            },
        ),
        migrations.CreateModel(
            name='UserListeningQuestionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(db_index=True, default=False, verbose_name='is favorited')),
                ('answer_payload', models.JSONField(blank=True, default=dict, verbose_name='answer payload')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='is correct')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='last answered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='exam_preparation.listeningquestion', verbose_name='question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_preparation_listening_question_states', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user listening question state',
                'verbose_name_plural': 'user listening question states',
                'ordering': ['-updated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='exam_prep_user_listen_q_state_uq')],
            },
        ),
        migrations.CreateModel(
            name='UserReadingAdMatchingItemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(db_index=True, default=False, verbose_name='is favorited')),
                ('answer_payload', models.JSONField(blank=True, default=dict, verbose_name='answer payload')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='is correct')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='last answered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='exam_preparation.readingadmatchingitem', verbose_name='item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_preparation_reading_ad_matching_item_states', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user reading ad matching item state',
                'verbose_name_plural': 'user reading ad matching item states',
                'ordering': ['-updated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='exam_prep_user_ram_item_state_uq')],
            },
        ),
        migrations.CreateModel(
            name='UserReadingTitleMatchingItemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(db_index=True, default=False, verbose_name='is favorited')),
                ('answer_payload', models.JSONField(blank=True, default=dict, verbose_name='answer payload')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='is correct')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='last answered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='exam_preparation.readingtitlematchingitem', verbose_name='item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_preparation_reading_title_matching_item_states', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user reading title matching item state',
                'verbose_name_plural': 'user reading title matching item states',
                'ordering': ['-updated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='exam_prep_user_rtm_item_state_uq')],
            },
        ),
        migrations.CreateModel(
            name='UserReadingUnderstandingQuestionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(db_index=True, default=False, verbose_name='is favorited')),
                ('answer_payload', models.JSONField(blank=True, default=dict, verbose_name='answer payload')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='is correct')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='last answered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='exam_preparation.readingunderstandingquestion', verbose_name='question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_preparation_reading_understanding_question_states', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user reading understanding question state',
                'verbose_name_plural': 'user reading understanding question states',
                'ordering': ['-updated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='exam_prep_user_ru_q_state_uq')],
            },
        ),
        migrations.CreateModel(
            name='UserSpeakingGapBlankState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(db_index=True, default=False, verbose_name='is favorited')),
                ('answer_payload', models.JSONField(blank=True, default=dict, verbose_name='answer payload')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='is correct')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='last answered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='exam_preparation.speakinggapblank', verbose_name='blank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_preparation_speaking_gap_blank_states', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user speaking gap blank state',
                'verbose_name_plural': 'user speaking gap blank states',
                'ordering': ['-updated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'blank'), name='exam_prep_user_sg_blank_state_uq')],
            },
        ),
        migrations.CreateModel(
            name='UserSpeakingPromptSegmentedExerciseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(db_index=True, default=False, verbose_name='is favorited')),
                ('answer_payload', models.JSONField(blank=True, default=dict, verbose_name='answer payload')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='is correct')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='last answered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='exam_preparation.speakingpromptsegmentedexercise', verbose_name='exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_preparation_speaking_prompt_segmented_exercise_states', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user speaking prompt segmented exercise state',
                'verbose_name_plural': 'user speaking prompt segmented exercise states',
                'ordering': ['-updated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'exercise'), name='exam_prep_user_sps_ex_state_uq')],
            },
        ),
        migrations.CreateModel(
            name='UserWritingExerciseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(db_index=True, default=False, verbose_name='is favorited')),
                ('answer_payload', models.JSONField(blank=True, default=dict, verbose_name='answer payload')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='is correct')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='last answered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='exam_preparation.writingexercise', verbose_name='exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_preparation_writing_exercise_states', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user writing exercise state',
                'verbose_name_plural': 'user writing exercise states',
                'ordering': ['-updated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'exercise'), name='exam_prep_user_write_ex_state_uq')],
            },
        ),
    ]
