# Generated by Django 6.0 on 2026-08-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_preparation', '0012_alter_exercisebase_exercise_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='speakinggapblank',
            name='exam_prep_sg_blank_key_uq',
        ),
        migrations.RemoveConstraint(
            model_name='speakinggapblank',
            name='exam_prep_sg_blank_num_uq',
        ),
        migrations.RemoveField(
            model_name='speakinggapmatchingexercise',
            name='exercise_base',
        ),
        migrations.RemoveConstraint(
            model_name='speakinggapoption',
            name='exam_prep_sg_opt_key_uq',
        ),
        migrations.RemoveConstraint(
            model_name='speakingpromptsegment',
            name='exam_prep_sps_segment_order_uq',
        ),
        migrations.RemoveField(
            model_name='speakingpromptsegmentedexercise',
            name='exercise_base',
        ),
        migrations.RemoveConstraint(
            model_name='userspeakinggapblankstate',
            name='exam_prep_user_sg_blank_state_uq',
        ),
        migrations.RemoveConstraint(
            model_name='userspeakingpromptsegmentedexercisestate',
            name='exam_prep_user_sps_ex_state_uq',
        ),
        migrations.AlterField(
            model_name='exercisebase',
            name='exercise_type',
            field=models.CharField(choices=[('LISTENING_TEIL1', 'Listening Teil 1'), ('LISTENING_TEIL2', 'Listening Teil 2'), ('LISTENING_TEIL3', 'Listening Teil 3'), ('READING_TITLE_MATCHING', 'Reading title matching'), ('READING_UNDERSTANDING', 'Reading understanding'), ('READING_AD_MATCHING', 'Reading ad matching'), ('CLOZE_CHOICE', 'Cloze choice'), ('CLOZE_MATCHING', 'Cloze matching'), ('WRITING_PROMPT', 'Writing prompt'), ('SPEAKING_TEIL1', 'Speaking Teil 1'), ('SPEAKING_TEIL2', 'Speaking Teil 2'), ('SPEAKING_TEIL3', 'Speaking Teil 3')], db_index=True, max_length=64, verbose_name='exercise type'),
        ),
        migrations.RemoveField(
            model_name='speakinggapblank',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='speakinggapoption',
            name='blank',
        ),
        migrations.RemoveField(
            model_name='speakingpromptsegment',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='userspeakinggapblankstate',
            name='blank',
        ),
        migrations.RemoveField(
            model_name='userspeakinggapblankstate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userspeakingpromptsegmentedexercisestate',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='userspeakingpromptsegmentedexercisestate',
            name='user',
        ),
        migrations.DeleteModel(
            name='SpeakingGapMatchingExercise',
        ),
        migrations.DeleteModel(
            name='SpeakingGapOption',
        ),
        migrations.DeleteModel(
            name='SpeakingPromptSegment',
        ),
        migrations.DeleteModel(
            name='SpeakingGapBlank',
        ),
        migrations.DeleteModel(
            name='UserSpeakingGapBlankState',
        ),
        migrations.DeleteModel(
            name='SpeakingPromptSegmentedExercise',
        ),
        migrations.DeleteModel(
            name='UserSpeakingPromptSegmentedExerciseState',
        ),
    ]
