from django.db import migrations


def lines(*values):
    return "<br>".join(values)


WRITING_CONTENT = {
    "1": {
        "request_text": lines(
            "Sie haben von einem Freund folgende E-Mail erhalten:",
            "",
            "Liebe(r) ...",
            "",
            "Nach unserem schönen gemeinsamen Erlebnis letztes Jahr möchte ich auch dieses Jahr wieder einen Ausflug für uns alle organisieren. Ich hoffe sehr, dass ihr Zeit habt und mitkommen könnt. Ich freue mich schon jetzt, euch alle bald wiederzusehen! Das Dumme ist nur, dass ich mir vor drei Wochen beim Basketball das Bein gebrochen habe und noch nicht so gut zu Fuß bin. Deshalb habe ich einen gemütlichen Ausflug mit Bus und Schiff geplant – hoffentlich ist dann auch das Wetter gut für die Schifffahrt! Wohin es geht, möchte ich euch aber noch nicht verraten – das soll eine Überraschung werden.",
            "",
            "Termin: übernächster Samstag.",
            "Zeit und Treffpunkt: 9:30 Uhr bei mir.",
            "",
            "Bitte schreibt mir doch, ob ihr beim Ausflug dabei sein könnt!",
            "",
            "Hoffentlich bis bald",
            "Thomas",
        ),
        "task_text": lines(
            "Antworten Sie Thomas. Schreiben Sie etwas zu allen vier Punkten:",
            "- Alternativvorschlag bei schlechtem Wetter",
            "- Einladung annehmen",
            "- Was Sie noch über den Ausflug wissen wollen",
            "- Auf den Sportunfall reagieren",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "2": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Entschuldige, dass ich mich erst jetzt wieder melde. Ich weiß, wir hatten ausgemacht, uns öfter mal zu schreiben, aber es war so viel los in letzter Zeit. Ich habe eine Neuigkeit für dich: Meine kleine Schwester Janine heiratet im Oktober, und ich habe ihr versprochen, schon einmal allen Freunden zu schreiben und Bescheid zu sagen. Die offizielle Einladung bekommst du natürlich noch von ihr direkt. Edii, ihr zukünftiger Mann, ist echt nett, und wir mögen ihn alle sehr. Er ist Koch und arbeitet hier in einem Hotel.",
            "",
            "Wir planen jetzt alles. Gib mir deshalb möglichst bald Bescheid, ob du kommst und mit wem.",
            "",
            "Herzliche Grüße",
            "Jennifer",
        ),
        "task_text": lines(
            "Antworten Sie Jennifer. Schreiben Sie etwas zu allen vier Punkten:",
            "- Reaktion auf die Neuigkeit",
            "- Übernachtungsmöglichkeit",
            "- Sie möchten zur Hochzeit kommen",
            "- Hochzeitsgeschenk",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "3": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Endlich habe ich Zeit, dir wieder einmal zu schreiben. Schade, dass du bei unserer Hochzeit nicht dabei sein konntest! Wir waren mit Freunden und Verwandten über 50 Personen. Ich habe ein langes weißes Kleid getragen, und Karl hat sich für diesen Tag einen teuren schwarzen Anzug gekauft, obwohl er sonst immer nur Jeans trägt. Natürlich gab es ein wunderbares Festessen, und danach wurde getanzt. Karl und ich haben viele Geschenke bekommen, vor allem auch Geld für unsere Hochzeitsreise. Wir wissen aber noch gar nicht, wohin wir fahren wollen.",
            "",
            "Wie läuft es eigentlich bei dir? Du hast doch eine neue Stelle. Wie gefällt dir die Arbeit? Karl und ich würden uns sehr freuen, wenn du uns wieder einmal besuchen würdest!",
            "",
            "Liebe Grüße",
            "Rita",
        ),
        "task_text": lines(
            "Antworten Sie Rita. Schreiben Sie etwas zu allen vier Punkten:",
            "- Ihre neue Arbeitsstelle",
            "- Wie man in Ihrem Land heiratet",
            "- Vorschlag für Ritas Hochzeitsreise",
            "- Rita und Karl besuchen",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "4": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Wie geht es dir und deiner Familie?",
            "",
            "Bei mir läuft alles prima. Endlich habe ich eine neue Arbeitsstelle. Ich habe nur ein kleines Problem: Es ist ein bisschen zu weit, um zu Fuß zu gehen. Der Bus fährt nur alle 30 Minuten. Früher bin ich meist mit dem Fahrrad gefahren, aber hier gibt es keine Fahrradwege. Und da ist ja auch noch mein Daniel, den ich morgens in den Kindergarten bringen muss. Der liegt zum Glück gleich neben meiner neuen Firma.",
            "",
            "Wie kommst du denn zur Arbeit oder zum Deutschkurs? Wollen wir uns nicht einmal wieder treffen und alle zusammen etwas unternehmen? Ich würde mich freuen.",
            "",
            "Liebe Grüße",
            "Vera",
        ),
        "task_text": lines(
            "Antworten Sie Vera. Schreiben Sie etwas zu allen vier Punkten:",
            "- Was es bei Ihnen Neues gibt",
            "- Wie Sie zur Arbeit kommen",
            "- Was Sie über Veras neue Stelle wissen wollen",
            "- Vorschlag für eine gemeinsame Unternehmung",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "5": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Ich sende dir ganz viele Grüße aus Rom! Du weißt ja, wie sehr mir diese Stadt gefällt. Ich bin hier von morgens bis abends nur unterwegs. Diese Museen, Parks, Plätze und natürlich das Essen sind wunderbar! Gestern Abend war ich übrigens bei einem Rockkonzert. Ich fand die Musik ganz toll, und die Stimmung war super.",
            "",
            "Doch leider ist mein Urlaub schon fast vorbei, und in drei Tagen muss ich wieder zurück nach Deutschland. Welche Stadt ist eigentlich deine Lieblingsstadt? Hast du schon Pläne für deinen nächsten Urlaub? Vielleicht können wir uns ja einmal wieder treffen.",
            "",
            "Herzliche Grüße",
            "Jan",
        ),
        "task_text": lines(
            "Antworten Sie Jan. Schreiben Sie etwas zu allen vier Punkten:",
            "- Ihre Lieblingsstadt",
            "- Welche Musik Sie mögen",
            "- Ihre Pläne für den nächsten Urlaub",
            "- Treffen mit Jan",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "6": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Heute habe ich Zeit, dir ein paar Zeilen zu schreiben. Der Urlaub war so schön, aber seit ich zurück bin, habe ich im Büro sehr viel Arbeit. Bestimmt brauche ich schon bald wieder Urlaub!",
            "",
            "Während ich weg war, hat sich hier übrigens einiges geändert: Es gibt einen neuen Kollegen, er heißt Roberto. Die größte Veränderung ist aber, dass er mit mir in meinem Büro arbeitet. Das heißt, ich habe endlich jemanden, mit dem ich mich zwischendurch auch ein bisschen unterhalten kann! Roberto ist aus Spanien hierhergezogen. Er kennt hier noch niemanden außer mir und ist meistens allein. Denkst du, dass ich ihn und ein paar andere Arbeitskollegen einmal einladen sollte? Was würdest du tun? Na gut, für heute muss ich Schluss machen. Melde dich doch bald einmal bei mir!",
            "",
            "Viele Grüße",
            "Andreas",
        ),
        "task_text": lines(
            "Antworten Sie Andreas. Schreiben Sie etwas zu allen vier Punkten:",
            "- Vorschlag, wie Andreas seinem Arbeitskollegen helfen kann",
            "- Wie Sie am liebsten arbeiten (allein oder mit Kollegen)",
            "- Was Sie nach dem Urlaub gemacht haben",
            "- Was es bei Ihnen Neues gibt",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "7": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Ich habe eine tolle Überraschung. Stell dir vor, was mir mein Onkel angeboten hat. Er rief mich am Samstag an. Er hat ein großes Ferienhaus im Schwarzwald. Das Haus kann ich für die Ferien kostenlos haben. Ich kann auch Freunde mitbringen! Wäre das nichts für uns? Wir könnten uns alle dort treffen: du, deine Eltern und Freunde und ich mit meiner Familie und meinen Freunden. Ich würde mich wahnsinnig freuen, wenn das klappen würde. Bitte schreibe mir so schnell du kannst, damit wir alles planen können. Urlaub im Schwarzwald – das wird traumhaft schön!",
            "",
            "Herzliche Grüße",
            "Petra",
        ),
        "task_text": lines(
            "Antworten Sie Petra. Schreiben Sie etwas zu allen vier Punkten:",
            "- Warum Sie gern in den Schwarzwald kommen möchten",
            "- Wie Sie anreisen wollen",
            "- Was Sie gemeinsam machen könnten",
            "- Wen Sie mitbringen möchten",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "8": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Du hast schon so lange nicht mehr geschrieben. Wie geht es dir? Heute habe ich eine Bitte. Vielleicht kannst du uns helfen?",
            "",
            "Eine 16-jährige Schülerin aus deinem Land wird uns besuchen und zwei Wochen bei uns in Goldbach bleiben. Natürlich möchten wir, dass sie sich wohlfühlt. Dein Land kennen wir nur aus deinen Erzählungen, denn wir waren selbst noch nicht dort. Bitte gib uns ein paar Informationen, zum Beispiel über typische Gewohnheiten oder typisches Essen. Was können wir tun, und wie können wir uns vorbereiten?",
            "",
            "Wir freuen uns schon auf deine Antwort.",
            "",
            "Schon einmal vielen Dank und liebe Grüße",
            "Caroline",
        ),
        "task_text": lines(
            "Antworten Sie Caroline. Schreiben Sie etwas zu allen vier Punkten:",
            "- Reaktion auf den Besuch der Schülerin",
            "- Vorschlag zu Essen und Trinken",
            "- Warum Sie so lange nicht geschrieben haben",
            "- Unternehmungen oder Programm mit der Schülerin",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "9": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Entschuldige, dass ich dir so lange nicht mehr geschrieben habe. Aber du weißt, mein älterer Bruder, der schon lange im Ausland lebt, ist jetzt für zwei Monate bei uns. Wir unternehmen einiges zusammen. Zum Beispiel gehen wir nachmittags ins Schwimmbad oder abends ins Kino.",
            "",
            "Wir verstehen uns eigentlich ganz gut, aber dennoch habe ich ein Problem mit ihm: Wenn es im Fernsehen eine Sportsendung gibt, dann bekomme ich ihn nicht mehr vom Fernseher weg! Er sitzt dann stundenlang nur da und sieht fern, ganz egal, wie schön das Wetter draußen ist! Was soll ich bloß tun? Soll ich überhaupt nichts sagen, oder soll ich deswegen mit ihm streiten? Er fährt bald wieder weg, und ich möchte doch mit ihm zusammen sein. Was würdest du machen?",
            "",
            "Hast du vielleicht ein paar Tipps oder Ratschläge für mich?",
            "",
            "Herzliche Grüße",
            "Nicole",
        ),
        "task_text": lines(
            "Antworten Sie Nicole. Schreiben Sie etwas zu allen vier Punkten:",
            "- Eigene Erfahrungen mit Geschwistern oder Freunden",
            "- Tipps für Nicole",
            "- Was Sie über den Bruder denken",
            "- Was Sie selbst gern gemeinsam mit anderen machen",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "10": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Ich sende dir sonnige Grüße von der wunderschönen Insel Malta. Katja, die Kinder und ich sind ganz glücklich! Strand, Kultur, Sport – all das ist hier möglich! Gestern haben wir uns sogar ein Auto gemietet und einen Ausflug gemacht. Auch für mein Hobby, das Fotografieren, habe ich sehr viel Zeit. Ich habe schon ganz viele Fotos gemacht. Ich schicke dir mit diesem Brief auch ein Buch über Malta, damit du siehst, wie interessant dieses Land ist. Hoffentlich gefällt dir das Buch.",
            "",
            "Leider ist unser Urlaub auch schon in wenigen Tagen vorbei. Wie wäre es? Vielleicht können wir uns ja wieder einmal treffen?",
            "",
            "Bis hoffentlich bald",
            "Viktor",
        ),
        "task_text": lines(
            "Antworten Sie Viktor. Schreiben Sie etwas zu allen vier Punkten:",
            "- Ihre Hobbys",
            "- Reaktion auf das Buch",
            "- Ihre Pläne für den nächsten Urlaub",
            "- Treffen mit Viktor",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "11": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Wir haben lange nichts mehr voneinander gehört. Ich hoffe, es geht dir gut. Gibt es bei dir Neuigkeiten? Ich bin nun schon seit zwei Monaten in Würzburg, und mein neuer Job gefällt mir sehr gut. In der Firma fühle ich mich wohl, mit meinen Kollegen verstehe ich mich prima, und die Arbeit macht mir großen Spaß.",
            "",
            "Allerdings habe ich ein Problem: Außer meinen Kollegen kenne ich hier in der Stadt noch niemanden. In meiner Freizeit bin ich oft allein und weiß nicht, was ich machen soll. Wie könnte ich neue Leute kennenlernen? Hast du vielleicht einen Tipp für mich?",
            "",
            "Würzburg ist wirklich eine schöne Stadt mit vielen Sehenswürdigkeiten. Hast du Lust, mich einmal an einem Wochenende zu besuchen? Ich würde mich sehr freuen.",
            "",
            "Viele Grüße",
            "Sophie",
        ),
        "task_text": lines(
            "Antworten Sie Sophie. Schreiben Sie etwas zu allen vier Punkten:",
            "- Was es bei Ihnen Neues gibt",
            "- Was Sie selbst gern in Ihrer Freizeit machen",
            "- Tipps für Sophie",
            "- Reaktion auf den Vorschlag",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "12": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Wie geht es dir? Du hast mir schon so lange nicht mehr geschrieben, dass ich mir Sorgen mache. Hoffentlich ist bei euch alles in Ordnung. Es wird wirklich Zeit, dass wir uns wiedersehen. Anfang des Jahres habe ich meinen Arbeitsplatz gewechselt. Meine neue Stelle ist sehr interessant, aber auch anstrengend.",
            "",
            "Ich bin nun beruflich sehr viel unterwegs. Demnächst muss ich auch in eure Gegend reisen. Dann könnten wir uns doch einmal am Abend treffen und gemeinsam etwas unternehmen. Wie findest du meine Idee? Ich würde auch sehr gern deine Familie kennenlernen.",
            "",
            "Bitte antworte mir bald!",
            "",
            "Herzliche Grüße",
            "Deine Tamara",
        ),
        "task_text": lines(
            "Antworten Sie Tamara. Schreiben Sie etwas zu allen vier Punkten:",
            "- Vorschlag für das Treffen",
            "- Jemanden mitbringen",
            "- Frage zur neuen Arbeitsstelle",
            "- Warum Sie nicht geschrieben haben",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "13": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Wie geht es dir? Hattest du ein schönes Wochenende? Hier hat es die ganze Zeit geregnet, deshalb bin ich zu Hause geblieben.",
            "",
            "Du hattest vorgeschlagen, dass wir im Sommer zusammen verreisen könnten. Die Idee finde ich super! An welches Reiseziel denkst du? Ich bin gern am Meer, mag aber auch Städtereisen. Wichtig ist für mich nur, dass ich auch ein bisschen Sport machen kann. Die Reise sollte aber nicht zu viel kosten, denn ich habe vor Kurzem schon viel für eine Autoreparatur bezahlen müssen. Was meinst du: Wie können wir günstig Urlaub machen? Es muss ja kein Luxushotel sein.",
            "",
            "Schreib mir bald, dann können wir anfangen zu planen.",
            "",
            "Viele Grüße",
            "Annika",
        ),
        "task_text": lines(
            "Antworten Sie Annika. Schreiben Sie etwas zu allen vier Punkten:",
            "- Was Sie am Wochenende unternommen haben",
            "- Wohin Sie gern reisen würden",
            "- Was Sie im Urlaub gern machen",
            "- Wie man beim Reisen Geld sparen kann",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "14": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Es tut mir wirklich leid, dass ich dir schon so lange nicht geschrieben habe. Bei mir ist im letzten Monat ziemlich viel los gewesen. Vor drei Wochen bin ich nämlich in eine neue Wohnung gezogen, weil die alte für mich zu klein war. Mittlerweile habe ich mich schon sehr schön eingerichtet, mit ein paar neuen Möbeln und so weiter. Ich fühle mich wirklich wohl! Hast du nicht Lust, mich im Sommer zu besuchen?",
            "",
            "In meiner neuen Wohnung habe ich jetzt auch ein kleines Arbeitszimmer für meine ganzen Bücher und den Schreibtisch mit dem Computer. Wie ist das bei dir? Machst du eigentlich viel am Computer?",
            "",
            "Lass doch einmal wieder etwas von dir hören!",
            "",
            "Liebe Grüße und bis bald",
            "Andreas",
        ),
        "task_text": lines(
            "Antworten Sie Andreas. Schreiben Sie etwas zu allen vier Punkten:",
            "- Ihre Erfahrungen mit dem Computer",
            "- Etwas über Ihre Wohnung",
            "- Ob Sie Andreas besuchen möchten",
            "- Was es bei Ihnen Neues gibt",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "15": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Die Sommerferien kommen rasch näher, und ich freue mich sehr, dass du mich besuchen kommst. Ich habe eine tolle Idee:",
            "",
            "Ich möchte dich gern zu einem Musikfestival einladen, und zwar nach Rüdesheim (ca. 50 km von Mainz entfernt). Dort spielen in diesem Sommer die besten internationalen Musikgruppen.",
            "",
            "Ich finde Open-Air-Konzerte einfach toll: die friedliche Stimmung unter den Besuchern, die gute Musik und einfach viele schöne Momente, die man nie mehr vergisst. Vor allem, wenn das Wetter gut ist, kann man das so richtig genießen.",
            "",
            "Wir könnten mit dem Zug nach Rüdesheim fahren oder auch mein Auto nehmen. Was wäre dir lieber? Übernachten würde ich gern auf dem Festplatz. Was meinst du? Und willst du vielleicht noch jemanden mitbringen? Vielleicht hast du noch einen Wunsch, was du sonst noch hier machen möchtest? Schreib mir bitte möglichst bald.",
            "",
            "Ich freue mich schon auf deine Antwort.",
            "",
            "Herzliche Grüße",
            "Sonja",
        ),
        "task_text": lines(
            "Antworten Sie Sonja. Schreiben Sie etwas zu allen vier Punkten:",
            "- Was Sie sonst noch machen würden",
            "- Wie Sie zum Festival fahren möchten",
            "- Ob Sie jemanden mitbringen möchten",
            "- Reaktion auf Sonjas Vorschlag zur Übernachtung",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "16": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Ich hoffe, dir geht es gut. Stell dir vor, bei mir gibt es Neuigkeiten. Du weißt doch, dass wir schon lange von einem Garten geträumt haben. Jetzt haben wir endlich einen am Stadtrand gefunden. Da er sehr groß ist, wollte ich dich fragen, ob du noch Lust hast, den Garten mit uns zu teilen.",
            "",
            "Die Miete ist gar nicht so hoch. Du könntest dort Salat und Gemüse anpflanzen, natürlich auch Blumen, ganz wie du willst. Es gibt auch Obstbäume und eine große Wiese, auf die man sich einfach legen kann. Wir könnten im Garten auch grillen. Was denkst du? Wäre das nicht toll? Antworte mir bald.",
            "",
            "Alles Liebe",
            "Deine Nadja",
        ),
        "task_text": lines(
            "Antworten Sie auf den Brief. Schreiben Sie etwas zu den folgenden vier Punkten:",
            "- Reaktion auf den Vorschlag",
            "- Fragen zum Garten",
            "- Weg zum Garten",
            "- Was es bei Ihnen Neues gibt",
            "",
            "Überlegen Sie sich eine passende Reihenfolge der Punkte, eine passende Einleitung und einen passenden Schluss.",
        ),
    },
    "17": {
        "request_text": lines(
            "Eine Bekannte aus der Schweiz hat eine neue Stelle. Sie hat Ihnen den folgenden Brief geschrieben:",
            "",
            "Liebe(r) ...",
            "",
            "Wie geht es denn so mit dem Deutschlernen? Kommst du gut voran, und was machst du im Moment so? Stell dir vor, ich habe die neue Stelle bei der Zeitschrift VIA bekommen! Ich arbeite jetzt als Journalistin, und das war ja immer mein Traumberuf!",
            "",
            "VIA wird vor allem von jüngeren Leuten gelesen. Deshalb schreiben wir viel über Berufe und Ausbildungen und auch über Freizeit und Sport. Für die nächsten Hefte von VIA planen wir jetzt eine neue Serie über Berufswünsche. Was ist eigentlich dein Traumberuf? Wenn du möchtest, schicke ich dir gern einmal ein Exemplar von VIA, damit du siehst, was ich so mache.",
            "",
            "Ich freue mich schon auf deine Antwort.",
            "",
            "Herzliche Grüße",
            "Eva",
        ),
        "task_text": lines(
            "Schreiben Sie Ihrer Bekannten nun einen Antwortbrief, der die folgenden Punkte enthält:",
            "- Fortschritte beim Deutschlernen",
            "- Auf Evas neue Stelle reagieren",
            "- Was es bei Ihnen Neues gibt",
            "- Ihr Traumberuf",
            "",
            "Bevor Sie den Brief schreiben, überlegen Sie sich eine passende Reihenfolge der Punkte, eine passende Einleitung und einen passenden Schluss.",
        ),
    },
    "18": {
        "request_text": lines(
            "Eine Bekannte hat Ihnen die folgende E-Mail geschrieben:",
            "",
            "Liebe(r) ...",
            "",
            "Endlich habe ich die Deutschprüfung hinter mir. Ich glaube, es ist gut gelaufen. Jetzt soll ich für unseren Kurs eine Party organisieren. Du hast doch kürzlich erzählt, dass du für euren Kurs auch ein Abschlussfest organisiert hast. Sicher kannst du mir ein paar Tipps geben. Ich habe mir gedacht, wir könnten vielleicht in einem Restaurant feiern. Da kann jeder essen und trinken, was er will. Was meinst du? Essen zu kochen ist doch ziemlich viel Arbeit. Und natürlich brauchen wir Musik. Welche Musik ist am besten geeignet? Was schlägst du vor?",
            "",
            "Melde dich bald.",
            "Ich freue mich schon auf deine Antwort.",
            "",
            "Liebe Grüße",
            "Iris",
        ),
        "task_text": lines(
            "Antworten Sie Ihrer Bekannten. Schreiben Sie etwas zu allen vier Punkten:",
            "- Reaktion auf die Prüfung",
            "- Ihre Meinung zu einer Feier im Restaurant",
            "- Welche Musik geeignet ist",
            "- Ihre Urlaubspläne",
            "",
            "Überlegen Sie sich vor dem Schreiben eine passende Reihenfolge der Punkte, einen passenden Betreff, eine passende Anrede, eine Einleitung und einen passenden Schluss.",
        ),
    },
    "19": {
        "request_text": lines(
            "Liebe(r) ...",
            "",
            "Über deinen Brief habe ich mich sehr gefreut. Ich finde es sehr interessant, was du von deiner Familie erzählst. Weißt du, ich habe nämlich keine Geschwister wie du. Darum kann ich mir gar nicht vorstellen, wie es ist, wenn so viele Leute in einem Haus wohnen. Aber ich glaube, es würde mir schon gefallen. Du erzählst gar nicht, was du sonst so den ganzen Tag machst. Schreibe mir doch bitte im nächsten Brief darüber, wie dein Alltag aussieht und was du in deiner Freizeit machst.",
            "",
            "Viele Grüße an deine Familie",
            "Deine Daniela",
        ),
        "task_text": lines(
            "Antworten Sie Ihrer Brieffreundin. Schreiben Sie in Ihrem Brief etwas zu allen vier Punkten:",
            "- Was Sie jeden Tag machen müssen",
            "- Wann und wie Sie den Tag beginnen",
            "- Wie Sie normalerweise Ihr Wochenende verbringen",
            "- Wie Sie den Abend verbringen",
            "",
            "Bevor Sie den Brief schreiben, überlegen Sie sich eine passende Reihenfolge der Punkte, eine passende Einleitung und einen passenden Schluss.",
        ),
    },
    "20": {
        "request_text": lines(
            "Sie haben von einer Freundin folgende E-Mail erhalten:",
            "",
            "Liebe(r) ...",
            "",
            "Vielen Dank für deine Einladung zu einem gemeinsamen Wochenende! Ich freue mich schon sehr darauf, dich wiederzusehen und Zeit mit dir zu verbringen. Ich habe allerdings ein paar Fragen, bevor ich meinen Besuch plane.",
            "",
            "Welche Aktivitäten hast du für uns geplant? Wie ist das Wetter normalerweise zu der Zeit? Welche Art von Kleidung sollte ich einpacken? Und gibt es sonst noch etwas, das ich vor der Reise wissen sollte? Ich freue mich auf deine Antwort.",
            "",
            "Beste Grüße",
            "Sophie",
        ),
        "task_text": lines(
            "Antworten Sie Sophie. Schreiben Sie in Ihrem Brief etwas zu allen vier Punkten:",
            "- Welche Aktivitäten Sie mit Sophie unternehmen möchten",
            "- Wie das Wetter zu der Zeit ist",
            "- Welche Kleidung Sophie einpacken sollte",
            "- Was Sophie vor der Reise wissen sollte",
            "",
            "Bevor Sie den Brief schreiben, überlegen Sie sich eine passende Reihenfolge der Punkte, eine passende Einleitung und einen passenden Schluss.",
        ),
    },
}


def polish_writing_prompts(apps, schema_editor):
    writing_exercise = apps.get_model("exam_preparation", "WritingExercise")
    for external_id, content in WRITING_CONTENT.items():
        writing_exercise.objects.filter(
            exercise_base__level="B1",
            exercise_base__skill="WRITING",
            exercise_base__exercise_type="WRITING_PROMPT",
            exercise_base__external_id=external_id,
        ).update(**content)


class Migration(migrations.Migration):
    dependencies = [
        ("exam_preparation", "0014_userspeakingturnstate"),
    ]

    operations = [
        migrations.RunPython(polish_writing_prompts, migrations.RunPython.noop),
    ]
