# Generated by Django 6.0 on 2026-09-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_preparation', '0015_polish_writing_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='clozechoiceblank',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='explanation'),
        ),
        migrations.AddField(
            model_name='clozechoiceblank',
            name='explanation_scope',
            field=models.CharField(choices=[('question', 'Question'), ('option', 'Option')], default='question', max_length=16, verbose_name='explanation scope'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='explanation'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='explanation_scope',
            field=models.CharField(choices=[('question', 'Question'), ('option', 'Option')], default='question', max_length=16, verbose_name='explanation scope'),
        ),
        migrations.AddField(
            model_name='readingunderstandingquestion',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='explanation'),
        ),
        migrations.AddField(
            model_name='readingunderstandingquestion',
            name='explanation_scope',
            field=models.CharField(choices=[('question', 'Question'), ('option', 'Option')], default='question', max_length=16, verbose_name='explanation scope'),
        ),
    ]
