# Generated by Django 6.0 on 2026-09-19 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_preparation', '0017_update_writing_word_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('exercise_selection', models.JSONField(default=dict)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('writing_text', models.TextField(blank=True, default='')),
                ('writing_grade', models.CharField(blank=True, default='', max_length=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_mock_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'fingerprint'), name='exam_prep_saved_mock_user_fingerprint_uq')],
            },
        ),
    ]
