# Generated by Django 6.0 on 2026-09-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_preparation', '0018_savedmockexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmockexam',
            name='exam_type',
            field=models.CharField(default='telc', max_length=128),
        ),
        migrations.AddField(
            model_name='savedmockexam',
            name='level',
            field=models.CharField(default='B1', max_length=8),
        ),
    ]
