# Generated by Django 6.0 on 2026-09-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_preparation', '0019_savedmockexam_exam_type_savedmockexam_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmockexam',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedmockexam',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
