# Generated by Django 6.0 on 2026-09-20 13:57

import apps.exam_preparation.models.mock_exam
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_preparation', '0022_savedmockexam_writing_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmockexam',
            name='is_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedmockexam',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='savedmockexam',
            name='score_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='savedmockexam',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='MockExamShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(default=apps.exam_preparation.models.mock_exam.generate_mock_exam_share_code, editable=False, max_length=15, unique=True)),
                ('share_mode', models.CharField(choices=[('paper', 'Paper only'), ('paper_with_answers', 'Paper with answers')], default='paper', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='exam_preparation.savedmockexam')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exam_shares', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='exam_preparation.mockexampaper')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'share_mode'), name='exam_prep_mock_share_attempt_mode_uq')],
            },
        ),
    ]
