# Generated by Django 6.0 on 2025-12-15 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_is_beta_tester_module_userdata_entitlement'),
        ('lexicon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('video_url', models.URLField(blank=True, default='')),
                ('cover_letter_url', models.URLField(blank=True, default='')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField(db_index=True, help_text='Start time in seconds.')),
                ('end', models.FloatField(help_text='End time in seconds.')),
                ('content', models.TextField()),
                ('translation', models.TextField(blank=True, default='')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='learning_by_video.video')),
            ],
            options={
                'ordering': ['video_id', 'start'],
            },
        ),
        migrations.CreateModel(
            name='LearningVideoUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_videos', models.PositiveIntegerField(default=0)),
                ('learning_days', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_video_data', to='accounts.userdata')),
                ('last_watched_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learning_by_video.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoExpressionOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.FloatField(db_index=True, help_text='Start time in seconds.')),
                ('time_end', models.FloatField(blank=True, help_text='End time in seconds.', null=True)),
                ('translation', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meaning', models.TextField(blank=True, default='')),
                ('example', models.TextField(blank=True, default='')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_occurrences', to='lexicon.expressiontext')),
                ('subtitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='learning_by_video.subtitle')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='learning_by_video.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progresses', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='learning_by_video.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSentenceOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.FloatField(db_index=True, help_text='Start time in seconds.')),
                ('time_end', models.FloatField(blank=True, help_text='End time in seconds.', null=True)),
                ('translation', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_occurrences', to='lexicon.sentencetext')),
                ('subtitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='learning_by_video.subtitle')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='learning_by_video.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoWordOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.FloatField(db_index=True, help_text='Start time in seconds.')),
                ('time_end', models.FloatField(blank=True, help_text='End time in seconds.', null=True)),
                ('translation', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='learning_by_video.subtitle')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='learning_by_video.video')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_occurrences', to='lexicon.wordtext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='subtitle',
            index=models.Index(fields=['video', 'start'], name='idx_sub_video_start'),
        ),
        migrations.AddIndex(
            model_name='videoexpressionoccurrence',
            index=models.Index(fields=['video', 'time_start'], name='idx_videoexpressionoccurrence_video_ts'),
        ),
        migrations.AddIndex(
            model_name='videoexpressionoccurrence',
            index=models.Index(fields=['subtitle', 'time_start'], name='idx_videoexpressionoccurrence_sub_ts'),
        ),
        migrations.AddIndex(
            model_name='videoexpressionoccurrence',
            index=models.Index(fields=['video', 'expression'], name='idx_veo_video_expr'),
        ),
        migrations.AddIndex(
            model_name='videoexpressionoccurrence',
            index=models.Index(fields=['subtitle', 'expression'], name='idx_veo_sub_expr'),
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['user', 'updated_at'], name='idx_progress_user_updated'),
        ),
        migrations.AddConstraint(
            model_name='videoprogress',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='uniq_user_video_progress'),
        ),
        migrations.AddIndex(
            model_name='videosentenceoccurrence',
            index=models.Index(fields=['video', 'time_start'], name='idx_videosentenceoccurrence_video_ts'),
        ),
        migrations.AddIndex(
            model_name='videosentenceoccurrence',
            index=models.Index(fields=['subtitle', 'time_start'], name='idx_videosentenceoccurrence_sub_ts'),
        ),
        migrations.AddIndex(
            model_name='videosentenceoccurrence',
            index=models.Index(fields=['video', 'sentence'], name='idx_vso_video_sentence'),
        ),
        migrations.AddIndex(
            model_name='videosentenceoccurrence',
            index=models.Index(fields=['subtitle', 'sentence'], name='idx_vso_sub_sentence'),
        ),
        migrations.AddIndex(
            model_name='videowordoccurrence',
            index=models.Index(fields=['video', 'time_start'], name='idx_videowordoccurrence_video_ts'),
        ),
        migrations.AddIndex(
            model_name='videowordoccurrence',
            index=models.Index(fields=['subtitle', 'time_start'], name='idx_videowordoccurrence_sub_ts'),
        ),
        migrations.AddIndex(
            model_name='videowordoccurrence',
            index=models.Index(fields=['video', 'word'], name='idx_vwo_video_word'),
        ),
        migrations.AddIndex(
            model_name='videowordoccurrence',
            index=models.Index(fields=['subtitle', 'word'], name='idx_vwo_sub_word'),
        ),
    ]
