# Generated by Django 6.0 on 2026-01-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_by_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tag strings associated with the video'),
        ),
    ]
