# Generated by Django 6.0 on 2025-12-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_by_video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='videoexpressionoccurrence',
            name='idx_videoexpressionoccurrence_video_ts',
        ),
        migrations.RemoveIndex(
            model_name='videoexpressionoccurrence',
            name='idx_videoexpressionoccurrence_sub_ts',
        ),
        migrations.RemoveIndex(
            model_name='videosentenceoccurrence',
            name='idx_videosentenceoccurrence_video_ts',
        ),
        migrations.RemoveIndex(
            model_name='videosentenceoccurrence',
            name='idx_videosentenceoccurrence_sub_ts',
        ),
        migrations.RemoveIndex(
            model_name='videowordoccurrence',
            name='idx_videowordoccurrence_video_ts',
        ),
        migrations.RemoveIndex(
            model_name='videowordoccurrence',
            name='idx_videowordoccurrence_sub_ts',
        ),
    ]
