# Generated by Django 6.0 on 2026-01-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_by_video', '0002_video_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoExerciseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', help_text='question_id from CSV (unique per video).', max_length=64)),
                ('question_type', models.CharField(choices=[('TRUE_FALSE', 'True False'), ('CHOICE', 'Choice')], db_index=True, max_length=16)),
                ('prompt', models.TextField(help_text='Question stem shown to the user.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_questions', to='learning_by_video.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoExerciseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Option text (CSV column: answer).')),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('explanation', models.TextField(blank=True, default='', help_text='Explanation for this specific option.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning_by_video.videoexercisequestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='videoexercisequestion',
            index=models.Index(fields=['video', 'order'], name='vxq_v_o'),
        ),
        migrations.AddConstraint(
            model_name='videoexercisequestion',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('video', 'external_id'), name='vxq_v_ext_uq'),
        ),
        migrations.AddIndex(
            model_name='videoexerciseoption',
            index=models.Index(fields=['question', 'order'], name='vxo_q_o'),
        ),
        migrations.AddIndex(
            model_name='videoexerciseoption',
            index=models.Index(fields=['question', 'is_correct'], name='vxo_q_c'),
        ),
        migrations.AddConstraint(
            model_name='videoexerciseoption',
            constraint=models.UniqueConstraint(fields=('question', 'text'), name='vxo_q_text_uq'),
        ),
    ]
