# Generated by Django 6.0 on 2026-01-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_by_video', '0003_videoexercisequestion_videoexerciseoption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='cover_url',
            new_name='cover_letter_url',
        ),
        migrations.AddField(
            model_name='video',
            name='creator',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
