# Generated by Django 6.0 on 2026-01-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_by_video', '0004_rename_cover_url_video_cover_letter_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='subtitle',
            constraint=models.UniqueConstraint(fields=('video', 'external_id'), name='sub_v_extid'),
        ),
    ]
