# Generated by Django 6.0 on 2026-02-03 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_by_video', '0005_subtitle_external_id_subtitle_sub_v_extid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningvideouserdata',
            name='completed_videos',
        ),
        migrations.CreateModel(
            name='LearningVideoUserVideoMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('favorited_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_video_user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_marks', to='learning_by_video.learningvideouserdata')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_marks', to='learning_by_video.video')),
            ],
            options={
                'indexes': [models.Index(fields=['learning_video_user_data', 'is_favorite'], name='idx_learning_video_mark_fav'), models.Index(fields=['learning_video_user_data', 'is_completed'], name='idx_learning_video_mark_completed'), models.Index(fields=['video', 'is_favorite'], name='idx_video_mark_fav')],
                'constraints': [models.UniqueConstraint(fields=('learning_video_user_data', 'video'), name='uniq_learning_video_userdata_video_mark')],
            },
        ),
    ]
