# Generated by Django 6.0 on 2026-02-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_by_video', '0006_remove_learningvideouserdata_completed_videos_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='learningvideouservideomark',
            name='uniq_learning_video_userdata_video_mark',
        ),
        migrations.RenameIndex(
            model_name='learningvideouservideomark',
            new_name='idx_lvu_mark_fav',
            old_name='idx_learning_video_mark_fav',
        ),
        migrations.RenameIndex(
            model_name='learningvideouservideomark',
            new_name='idx_lvu_mark_comp',
            old_name='idx_learning_video_mark_completed',
        ),
        migrations.AddConstraint(
            model_name='learningvideouservideomark',
            constraint=models.UniqueConstraint(fields=('learning_video_user_data', 'video'), name='uniq_lvu_video_mark'),
        ),
    ]
