# Generated by Django 6.0 on 2026-03-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_by_video', '0009_video_access_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoexpressionoccurrence',
            name='selected_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videowordoccurrence',
            name='selected_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
