# Generated by Django 6.0 on 2026-03-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_by_video', '0010_videoexpressionoccurrence_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningVideoUserSubtitleFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_video_user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_favorites', to='learning_by_video.learningvideouserdata')),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='learning_by_video.subtitle')),
            ],
            options={
                'indexes': [models.Index(fields=['learning_video_user_data', 'created_at'], name='idx_lvu_subfav_ct')],
                'constraints': [models.UniqueConstraint(fields=('learning_video_user_data', 'subtitle'), name='uniq_lvu_subtitle_fav')],
            },
        ),
    ]
